package web;

import java.util.*;
import java.io.IOException;
import java.io.PrintWriter;
import java.sql.*;

import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;

public class InsertAcq extends HttpServlet {

	public void doPost (HttpServletRequest request, HttpServletResponse response)  {
		this.insertRows(request, response);
	}

	public void doGet (HttpServletRequest request, HttpServletResponse response)  {
		this.insertRows(request, response);
	}

	public void insertRows(HttpServletRequest request, HttpServletResponse response) {
		try  {
			PrintWriter writer = response.getWriter();
            ApplicationContext ctx = new ClassPathXmlApplicationContext("web/acq-ann-context.xml");
            AcqDao acqDao = (AcqDao) ctx.getBean("acqDao");
			writer.println("<html><body>");
			Salutation salutation = Salutation.MR;
			String fname = request.getParameter("fname");
			String lname = request.getParameter("lname");
            String mi = request.getParameter("mi");
            String street = request.getParameter("street");
            String street2 = request.getParameter("street2");
            String city = request.getParameter("city");
            String state = request.getParameter("state");
            String zip = request.getParameter("zip");
            String homePhone = request.getParameter("homePhone");
            String dayPhone = request.getParameter("dayPhone");
            String cellPhone = request.getParameter("cellPhone");
            String email = request.getParameter("email");
            String spouse = request.getParameter("spouse");
            String comments = request.getParameter("comments");	
            Acquantance acq = new Acquantance(salutation, fname, mi, lname, street, street2, city, state, zip, homePhone, dayPhone, cellPhone, email, spouse, comments);
			acqDao.addPerson(acq);
			writer.println("<br>Added acquantance "+fname+" "+lname);
			writer.println("</body></html>");
			writer.close();
		} catch(IOException e) {
			e.printStackTrace();
		} catch(Exception e)  {
			e.printStackTrace();
		}
	}

	public void doBatch(Statement stmt) throws SQLException {
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Serap', '', '', '', '', '', '', '', '(301) 654-1107', '', '', '', '')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Pam', '', '', '', '', '', '', '', '(912) 922-2694', '', '', '', '')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Hoa', '', '', '', '', '', '', '', '(301) 890-7906', '(301) 681-3561', '', '', '')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Dao An', '', '', '', '', '', '', '', '(703) 680-3134', '', '', '', '')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Travis', 'Adkins', '', '', '', '', '', '', '(703) 527-7621', '(703) 553-7300', '', '', '')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('David', 'Allan', '', '9120 Wooden Bridge Rd.', '', 'Potomac', 'MD', '20854', '', '', '', '', '')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Chatkan', 'Bunnag', '', '9017 Garland Ave.', '', 'Silver Spring', 'MD', '20901', '(301) 588-3120', '(301) 948-5144', '', '', '')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Fish', 'Carter', '', '5 Grandview Ave.', '', 'Lake Placid', 'NY', '12946', '', '', '', '', '')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Michael', 'Chang', '', '6 Cedarhurst Circle', '', 'Lancaster', 'PA', '17603-6407', '', '', '', '', '')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Crowly', 'Colleen', '', '', '', '', '', '', '(703) 560-2798', '', '', '', '')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Ray', 'Coutant', '', '', '', '', '', '', '(703) 670-5048', '(703) 359-0032', '', '', '')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Dave', 'Cox', '', '94 Nottingham Rd.', '', 'Columbus', 'OH', '43214-2036', '614-267-1844', '', '', 'Renee', 'home phone may be apocrypal')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Griffin', 'Diana', '', '', '', '', '', '', '(912) 923-2987', '', '', '', '')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Duc Tuan', 'Do', '', '2125 N. George Mason Dr.', '', 'Arlington', 'VA', '22207', '', '', '', '', '')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Winthrop', 'Follansbee', '', '3 Nordling Lane', '', 'Madison', 'NJ', '07940', '', '', '', '', '')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Carla', 'Friedrich', '', '923-B Cherry St.', '', 'Macon', 'GA', '31201', '(912) 750-1035', '', '', '', '')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Trinh', 'Hendrikson', '', '3421 N. Edison St.', '', 'Arlington', 'VA', '22207', '(703) 527-4461', '(703) 848-6886', '', 'Donn', '')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Bau Xy', 'Ho', '', '1830 N. Columbus St.', '', 'Arlington', 'VA', '22207', '703-626-7076', '703-525-8433', '', 'Denise', 'AKA Daniel')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Ray', 'Kidder', '', '13312 Vista Forest Dr.', '', 'Lake Ridge', 'VA', '22192', '(703) 878-4912', '703-882-0896', 'ray.kidder@netzero.com', '', 'cell 703-498-8942')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Wayne', 'Kuenzli', '', '4001 N. 9th St. #212', '', 'Arlington', 'VA', '22203', '(703) 528-8329', '', '', '', '')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Mars', 'Larry', '', '333 Thornall St., 2nd Floor', '', 'Edison', 'NJ', '08837', '', '(201) 321-9200', '', '', '')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Trevor', 'Lauer', '', '', '', '', '', '', '(202) 986-6389', '(703) 749-2095', '', '', '')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Pete', 'LeGro', '', '', '', '', '', '', '(921) 922-0423', '', '', '', '')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Liu', 'Lin-Fei', '', '1702 Ohio St., #1', '', 'Lawrence', 'KA', '66044', '', '', '', '', '')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Ted', 'Litty', '', '4412 Chestnut St.', '', 'Bethesda', 'MD', '20814', '', '', '', 'Laura', '')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Bill', 'McGinnis', '', '1809 Melbourne Dr.', '', 'McLean', 'VA', '22101', '703-587-7736', '202-231-1052', 'z3mcg@yahoo.com', 'Setsuko', 'Former address: 1201 N. Garfield St., #516, Arlington, VA 22201')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Eric', 'Messick', '', '15139 Old Ranch Rd.', '', 'Los Gatos', 'CA', '95030', '(408) 353-4751', '(408) 727-2220', '', '', '')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Morris', 'Kastiyel', '', '1739 Hood Lane', '', 'Maple Glen', 'PA', '19002', '(215) 654-0627', '(609) 488-5086', 'kastiyel@erols.com', 'Lois', '')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Gautham's', 'Parents', '', '4471 Alta Tupelo Dr.', '', 'Calabasas', 'CA', '91302', '(818) 887-0226', '', '', '', '')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Kishor', 'Patel', '', '6110 Hayshire Cr.', '', 'Gaithersburg', 'MD', '20878', '', '(301) 961-6717', '', '', '')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Ly', 'Phan', '', '', '', 'Germantown', 'MD', '', '', '', '', 'Amy', '')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Gautham', 'Reddy', '', '??????', '', '?????', '??', '?????', '415-681-6467', '', '', 'Gayatri', '')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Melody', 'Roberts', '', '720 Tidewater Circle', '25D', 'Macon', 'GA', '31211', '478-742-3617', '478-926-7700', 'melodyroberts1@juno.com', '', 'day extension is 4150, other # 478-254-3988')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Twylia', 'Fannin', '', '574 Inverary Ct.', '', 'Lorton', 'VA', '22079', '(703) 339-5430', '', '', '', '')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Joe', 'Wang', '', '', '', '', '', '', '(201) 857-3918', '(212) 576-8136', '', 'Sue', '')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Mike', 'Wengryn', '', '', '', '', '', '', '(213) 438-8281', '', '', '', '')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Xianghuan', 'Xiang', '', '5240 Sherier Pl.', '', 'Washington', 'DC', '20016', '(202) 362-7628', '', '', 'Zhu Zhei-Wei', 'Spouse's Telephone No.:  (313) 763-8454')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Sarah', 'Xie', '', '14811 Dufief Mill Rd.', '', 'Gaithersburg', 'MD', '20878', '(301) 251-1011', '301-548-6840', 'sarah.xie@hughes.com', 'Sean', 'Fax: 240-453-2201, Cell 202-215-5862')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Jane', 'Ziki', '', '1806 Wyoming Ave.', '', 'Washington', 'DC', '20009', '', '', '', '', '')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Feng', 'Gao', '', '', '', '', '', '', '(301) 864-2415', '', '', '', 'Was in International Finance with me')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Geoff', 'Fuller', '', '', '', '', '', '', '301-279-5705', '703-415-4728', '', '', '')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Records', 'Birth', '', '177 S. Broadway St.', '', 'Akron', 'OH', '44308', '', '', '', '', '')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Nat', 'Kidder, Jr', 'R', '1027 Bond St.', '', 'Macon', 'GA', '31201', '', '', '', '', 'Old Georgia address')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Phil', 'Wang', '', '11309 Coral Gables Dr.', '', 'N. Potomac', 'MD', '20878-3804', '(301) 340-2118', '', 'phiipwang77@hotmail.com', 'Minchi', 'Legal Name: Chanyuan')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Bart', 'Keinlein', '', '4800 Woodshire Garth', '', 'Ellicott City', 'MD', '21043', '', '', '', '', '')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Michael', 'Haddad', '', '18945 Cross Country Lane', '', 'Gaithersburg', 'MD', '20879', '330-4078', '', '', 'Theresa', '')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('', 'McHenry', '', '14 Bitterroot Ct.', '', 'Rockville', 'MD', '20853', '', '972-628-5526', '', '', 'Former residents at 4935')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Nihat', 'Tourumtay', '', '9815 Bristol Square Ln. #103', '', 'Bethesda', 'MD', '20814', '', '', '', '', '')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Deirdre', 'Russell', '', 'PO Box 10846', 'Apt. B', 'Prescott', 'AZ', '86304', '', '', '', '', 'old addr: 1124 Stetson Road, Prescott, AZ 86303')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Melinda', 'Shiner', '', 'Rte 2, Box 53B', '', 'Lovettsville', 'VA', '20180', '', '', '', '', '')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Jennifer', 'Zembower', '', '10103 LeFevre Dr.', '', 'Cheltenham', 'MD', '20623-1030', '301-372-8753', '', '', '', '')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('John', 'Oravec', '', '4925 Melinda Ct.', '', 'Rockville', 'MD', '20853', '', '', '', 'Marlina', '')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Maritza', 'Matheus', 'E', '1805 Alberti Dr.', '', 'Silver Spring', 'MD', '20902-3363', '', '', '', 'Robert A. Sobolewski', 'classmate in high school')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Lu', 'Lu', '', '', '', '', '', '', '', '', '', '', 'llu@aol.com')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Hop', 'Campbell', 'T', '4515 Willard Ave.', '719', 'Chevy Chase', 'MD', '20815', '', '410-627-2188', '', '', 'Diana's Friend.  Ne Hop Pham')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Cosimo', 'Greco', '', '5528 Carville Ave.', '', 'Baltimore', 'MD', '21227-2805', '', '', '', 'Kathleen', '')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Jim', 'Wilson', '', '', '', '', '', '', '3014241628', '', '', '', 'Home number could also be 301-424-4628.  Head usher at Christ Church Rockville.')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Diana', 'Kidder', '', '21236 Crab Orchard Ct.', '', 'Ashburn', 'VA', '20147-4905', '703-723-0559', '703-723-0559', 'dianakidder@yahoo.com', 'Nat', 'The best wife and mother in the world.')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Ken', 'Reid', '', '607 Talmadge Ct.  SE', '', 'Leesburg', 'VA', '20175', '703-669-8789', '', 'reidkd@verizon.Net', '', 'Former M2X chair')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Bonnie', 'Shute-Reifsnyder', '', '6127 N. 18th St.', '', 'Arlington', 'VA', '22205', '', '', '', '', 'was on adoption trip')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('James', 'Tamura', '', '505 Shortridge Dr.', '', 'Wynnewood', 'PA', '19096', '', '', '', 'Sara Organic', 'former resident of 4935 Melinda Ct.')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Rick', 'Durkee', '', '510 Polling House Rd.', '', 'Annapolis', 'MD', '20776', '410-867-1153', '202-822-2450', '', '', '')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('David', 'Hodge', '', '', '', 'Springfield', 'VA', '', '', '', '', '', 'director of accounting, ORBCOMM')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Michael', 'Ferrier', '', '20759 Citation Dr.', '', 'Ashburn', 'VA', '20147', '', '', '', '', '')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Steven', 'Wells', '', '12044 Citation Hwy.--NO LONGER', '', 'Linden', 'VA', '22642', '5406357773', '', '', '', 'Have moved')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Terri', 'Miles', '', '20112 Hardwood Terrace', '', 'Ashburn', 'VA', '20147', '7037231916', '', '', '', '')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Elizabeth', 'Ambler', '', '100 Guilford Way', '', 'Atlanta', 'GA', '30350', '770-396-7275', '', '', '', 'Currently an accountant    404-210-5291   602-374-4454')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Lexi', 'Barrington', '', '12227 Parkstream Terrace', '', 'Herndon', 'VA', '22070', '', '', '', '', '')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Tim', 'Kloc', '', '44931 Falcon Pl.', '', 'Sterling', 'VA', '20166', '', '', '', '', '')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Tony', 'Aram', '', '4014 Kloman St.', '', 'Annandale', 'VA', '22003', '', '', '', 'Thu', '')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Thai', 'Tam Minh', '', '7701 Geogia Ave., NW', '#502', 'Washington', 'DC', '20012-1627', '', '', '', '', '')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('David', 'Russell', '', '9830 Camino Villa', '1016', 'San Antonio', 'TX', '78250', '2106820480', '', '', '', '')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Bruce', 'Shoop', '', '????', '', 'Rockville', 'MD', '????', '3017746381', '', '', '', 'Somewhere in Manor Woods')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('John', 'Rhoades', '', '3470 Bayside Walk', '', 'San Diego', 'CA', '92109-7545', '8584888973', '6197651921', '', 'Carmel', '')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Hue Tam', 'Ho Tai', '', '11 Forest St.', '', 'Cambridge', 'MA', '02140-1501', '', '', '', '', '')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Emily', 'Melgren', '', '4909 Melinda Ct.', '', 'Rockville', 'MD', '20853', '301-871-9110', '', '', 'Eric Williams', 'lives in Matt & Kim's old house.  Eric's father has Raven season tickets.')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Bill', 'Banford', '', '4915 Live Oak Ct.', '', 'Dumfries', 'VA', '22026', '7036805972', '', '', 'Robin', 'members of Ray Kidder's church, adopted from China in 2/2000')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Catholic', 'Charities', '', '1 E. Mt. Royal Ave', '', 'Baltimore', 'MD', '21202', '', '', '', '', 'Center for Family Services')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Holt', 'Intl', '', 'PO Box 2880', '', 'Eugene', 'OR', '97402', '', '', '', '', '')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Lenor', 'Ericson', '', '3730 Amsterdam Rd.', '', 'Manhattan', 'MT', '59741', '4062827446', '', '', 'Dave', 'Melody Robert's sister')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Day', 'Barth', '', '1 Apple Blossom Lane', '', 'Charles Town', 'WV', '25414', '304-725-7947', '240-446-7748', 'jedaya@comcast.net', '', 'was Dragn5528@aol.com')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Kim', 'Trinh', '', '7218 Farr St.', '', 'Annandale', 'VA', '22003', '', '703-750-9339', 'thienkim_trinh@hotmail.com', 'Mark Weldon', 'Acct no. is 110848539')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Jaye', 'Andrews', '', '3209 Milton Ave.', '', 'Dallas', 'TX', '75205', '2142655701', '', 'andrewsj@greenhill.org', '', '3209 Milton Ave, Dallas, Tx  75205	214-265-5071')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Catherine', 'Nguyen', '', '335 N. Madison St.', '', 'Arlington', 'VA', '22203-1032', '', '', '', '', '')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('John', 'Munson', '', '2267 Antler Lake Lane', '', 'Milltown', 'WI', '54858-2824', '', '', '', '', 'was on adoption trip')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Ruth', 'Jump', '', '4921 Melinda Ct.', '', 'Rockville', 'MD', '20853-2229', '3014605016', '', '', '', '')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Suzanne', 'Nosworthy', '', 'PO Box 1949', '', 'Kilmarnock', 'VA', '22482', '', '', '', '', '')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Elba', 'Martinez', 'J', '8808 Hidden Hill Lane', '', 'Potomac', 'MD', '20854', '', '3012997200', '', '', '')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Pete', '', '', '', '', '', '', '', '', '', '', '', '')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('John', 'Tyson', '', '23 Braxton Dr.', '', 'Sterling', 'VA', '20165', '7034444584', '', '', '', '')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Allan', 'Ho', '', '', '', '', '', '', '', '703-895-1329', '', '', 'cell 703-365-2452 or  571-535-8482')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Abel', 'Ho', '', '', '', '', '', '', '', '240-401-0766', '', '', '')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Jennifer', 'Jewett', '', '', '', '', '', '', '', '703-297-0835', '', '', '')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('G', 'Gancayco', 'P', '3800 Bel Pre Rd. #1', '', 'Silver Spring', 'MD', '20906', '', '3014603600', '', '', '9701 New Church St, Damascus, MD 20872 Phone: (301) 253-2128')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Emily', 'Wen', '', '', '', '', '', '', '3019168968', '', 'ewen@nfcr.org', '', 'Met her at Lakeforest Mall Sat 4/5 when they did the ethnic dances.  Has a boy younger than Emily.')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Roy', 'Beyer', '', '', '', '', '', '', '3019293371', '', '', '', '')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Victor', 'Bradford', '', '', '', '', '', '', '', '3014455900', '', '', '(C) 301-785-8777 (direct) 301-431-6188')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Michael', 'Peden', '', '', '', '', '', '', '3017765644', '', '', '', 'Can rebuild the column')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Dave', 'Matthews', '', 'Melinda Ct.', '', 'Rockville', 'MD', '20853', '3016038098', '3015293790', '', '', 'Next door neighbor')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Nguyen Van', 'Thang', '', '714 Lenmore Ave', 'B34', 'Rockville', 'MD', '20850', '', '', '', '', 'Maman Ho's friend')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('John', 'Greene', '', '4935 Melinda Ct.', '', 'Rockville', 'MD', '20853-2229', '301-460-6580', '', '', 'Carol', 'bought our house')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Tai', '', '', '', '', '', '', '', '', '240-304-6844', '', '', 'Diana's father's sister's son.  Owns casino operation, and his son is a dentist in New Jersey.  Number is cell.')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Page', 'Kidder', '', '25 E. South St.', '', 'Frederick', 'MD', '21701', '301-668-0452', '301-473-2426', '', '', 'Nat's mother')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Aubrey', 'Keith', '', '21233 Crab Orchard Ct.', '', 'Ashburn', 'VA', '20147', '703-724-7411', '', '', '', 'Daughter of Mr. MacArio, whose last name they are listed under in the phone book.')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Donna', 'Slingluff', '', '4928 Melinda Ct.', '', 'Rockville', 'MD', '20853', '301-460-5909', '301-460-5909', 'donnaslingluff@comcast.net', 'Bob', 'Neighbors across Melinda Ct.  Sells us herbal supplements.')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Jimmy', 'Ho', '', '8569 Daltons Grove Way', '', 'Bristow', 'VA', '20136', '703-944-8904', '', '', '', '')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Mike', 'Blefko', '', '21237 Crab Orchard Ct.', '', 'Ashburn', 'VA', '20147', '703-729-2251', '703-851-7157', 'michael.blefko@ngc.com', 'Denise', '')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Elizabeth', 'Simms, MD', '', '44035 Riverside Pkwy.', '300', 'Leesburg', 'VA', '20176', '', '703-444-3019', '', '', 'Diana's oncologist')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Robert', 'Ahmed, MD', 'F', '4001 Fair Ridge Dr., #304', '', 'Fairfax', 'VA', '22033', '', '703-359-8640', '', '', 'Diana's oncological surgeon')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Hanne', 'Dietrich', '', '180 Apple Blossom Ln', '', 'Charles Town', 'WV', '25414-4350', '', '', '', '', '')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Linda', 'Haslam', '', '11837 Waples Mill Rd.', '', 'Oakton', 'VA', '22124', '', '', 'lhaslam@terrestar.com', 'Chris', 'Former boss at Motient')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Janice', 'Butts', '', '19385 Cypress Ridge Ter.', '117', 'Leesburg', 'VA', '20176-5163', '703-723-0482', '', '', 'Harry', 'ne Janice Kidder, at Our Saviours Way')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('William', 'Wheatley', '', '7607 Gaylord Dr', '', 'Annandale', 'VA', '22003', '703-658-3044', '', 'Ingricita5@verizon.net', '', 'William.wheatley@dia.mil')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Carol', 'Stowell', '', '43115 Waxpool Road', '', 'Ashburn', 'VA', '20148', '', '', '', '', 'Office manager at Our Saviors Way')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Charles', 'Kidder', '', '8708 Polara Pl', '', 'Rockville', 'MD', '20855', '301-330-0479', '', 'charleskidder@yahoo.com', '', 'Francine's cell: 240-246-5075')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Darcy', 'Garthwaite', '', '', '', '', '', '', '703-724-7768', '703-622-1367', '', '', 'Works at Open Arms.  Has 4 kids and golfs.  Will take Emily off our hands if need be.')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Irene', 'Knowles', '', '19375 Cypress Ridge Terrace', '107', 'Leesburg', 'VA', '20176-5183', '', '', '', '', '')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Jacqueline', 'Trinh', '', '3101 Chichester Lane', '', 'Fairfax', 'VA', '22031', '', '', 'rvpkimtrinh@yahoo.com', '', '')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Joe', 'Luby', '', '21224 Crab Orchard Ct.', '', 'Ashburn', 'VA', '20147', '703-726-0033', '703-980-3519', '', 'Teresa', '')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Rick', 'Lash', '', '21240 Crab Orchard Ct.', '', 'Ashburn', 'VA', '20147-4905', '703-724-9322', '571-280-4495', '', '', 'Cell: 703-618-0183')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('ComputerAid', '', '', '1390 Ridgeview Ave.', '', 'Allentown', 'PA', '18140-9940', '', '', '', '', '')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('John', 'Maida', '', '1802 Kuser Road', 'Apt. 9', 'Hamilton', 'NJ', '08690', '', '', '', '', 'One of the Hunan 9 families.  She is a diabetic.')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Daniel', 'Lee', '', '14 Washington Ct.', '', 'Towaco', 'NJ', '07082', '', '', '', 'Mary', 'Part of Hunan 9.  Chinese who speak with a NY accent')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Corrado', 'Dugo', '', '21212 Tiger Lily Place', '', 'Ashburn', 'VA', '20147-5434', '', '', '', 'Sharon', '')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Sarah', 'Pelligrini', '', '22877 Ashton Woods Dr.', '', 'Brambleton', 'VA', '20148', '703-327-1687', '703-786-7212', '', 'Karl', 'C 703-855-2275')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Johnnie', 'Stubbs', '', '19673 Stanford Hall Place', '', 'Ashburn', 'VA', '20147', '', '', '', 'Eva', '')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Nathan', 'Martin', '', '4311 Medallion Dr.', '', 'Silver Spring', 'MD', '20904', '', '', '', 'Natalie', '')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Fred', 'Haas', '', '4924 Melinda Ct.', '', 'Rockville', 'VA', '20853-2229', '', '', '', 'Kathleen', '')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('John', 'Amler', '', '1437 E. Marshall Ave.', '', 'Phoenix', 'AZ', '85014', '', '', '', 'Elizabeth', '')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Jack', 'Dawson', '', '21232 Crab Orchard Ct.', '', 'Ashburn', 'VA', '20147', '', '', 'jdaws83395@aol.com', 'Suzanne', '')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Rapalee', 'Nancy', '', '1301 Columbia Rd.', '', 'Woodbridge', 'Va', '22191-2909', '', '', '', '', '')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Wei', 'Shi', '', '3419 E. Kachina Dr.', '', 'Phoenix', 'AZ', '85044', '', '', '', '', '')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Kidder', 'Clark', '', '4137 Sandstone Dr.', '', 'Janeville', 'WI', '53546', '608-931-6004', '', 'cokidder@charter.net', '', '')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Elizabeth', 'Ambler', 'K', '1437 East Marshall Ave.', '', 'Phoenix', 'AZ', '85014', '602-374-4454', '404-210-5291', 'Elizambler@aol.com', '', '')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Amanda', 'Tran', '', '43703 Lucketts Bridge Cir.', '', 'Ashburn', 'VA', '20148-6742', '', '', '', '', '')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Jamie', 'Foster', '', 'US Embassy Bangkok', 'RMO Box 66', 'APO AD', '', '96546', '', '', '', 'Thailand', 'need $.75 postage for letter')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Clark', 'Kidder', '', '1620 Sienna Crossing', '', 'Janesville', 'WI', '53546', '608-931-6004', '', 'cokidder@charter.net', '', 'Distant cousin')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('A Recovering', 'American Soldier', '', 'Walter Reed Medical Center', '6900 Georgia Ave., NW', 'Washington', 'DC', '20307-5001', '', '', '', '', '')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Jeff', 'Hale', '', '21229 Crab Orchard Ct.', '', 'Ashburn', 'VA', '20147', '', '', '', 'Kelly', '')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Troy', 'Taggart', '', '21220 Crab Orchard Ct.', '', 'Ashburn', 'VA', '20147', '703-371-6655', '703-371-6650', '', '', 'Spouse: Linda.  Possible other number: 703-729-2388.')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Shiv', 'Kuncham', '', '', '', '', '', '', '703-725-1160', '', 'kuncham@yahoo.com', '', '')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Amy', 'Newgen', '', '', '', '', '', '', '', '', 'newgena66@yahoo.com', '', 'Ly Phan's ex-wife')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Phuc', 'Nguyen', '', '', '', '', '', '', '', '', 'phucnga@hotmail.com', '', 'live in same neighborhood as Ray & Isabelle (in Lake Ridge)')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Hollie', 'Lopes', '', '7604 Serenade Circle', '', 'Clinton', 'MD', '20735', '', '', 'Lopes@enews.nrl.navy.mil', '', '')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Ahn', 'Tran', '', '18574 Norborne Ct.', '', 'Leesburg', 'VA', '20176', '703-669-6961', '202-884-8184', 'atran@aed.org', '', 'cell: 571-216-2383')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Bao', 'Anh', '', '', '', '', '', '', '703-537-8520', '703-507-3142', 'baby-catherine@hotmail.com', '', '')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('', '', '', '', '', '', '', '', '', '', '', '', '')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Hao', '', '', '', '', '', '', '', '703-671-3480', '571-243-1507', '', '', '')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('', 'Bartalone', '', '', '', '', '', '', '703-999-0454', '703-589-6000', '', '', 'day could be 703-585-6000')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Bich & Thanh', 'Ho', '', '', '', '', '', '', '626-794-4606', '', '', '', '')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Nancy', 'Borchert', '', '', '', '', '', '', '703-723-0587', '', 'nborchert@earthlink.net', '', '')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Nhat', '', '', '', '', '', '', '', '301-526-5472', '', '', '', '')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Kim', 'Ngan', '', '', '', '', '', '', '', '703-228-1511', '', '', 'cell 571-214-6112')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Stacey', 'Marsh', '', '20900 Fowlers Mill Circle', '', 'Ashburn', 'VA', '20147', '', '', '', '', '')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Shannon', 'Nalley', '', '43948 Kitts Hill Terr', '', 'Ashburn', 'VA', '20147', '703-723-8405', '703-501-2081', '', '', '')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Helene', 'Kuoh', '', '', '', '', '', '', '703-941-8995', '240-350-3075', 'HeleneKuoh@yahoo.com', '', '')");
		stmt.addBatch("INSERT INTO ACQUANTANCE (fname, lname, mi, street, street2, city, state, zip, homePhone, dayphone, email, spouse, comments) VALUES ('Tim', 'Owen', '', '44095 Rising Sun Terr', '', 'Ashburn', 'VA', '20147', '', '', '', 'Linda Li', '')");
		stmt.executeBatch();
	}
}