
package clientA;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "RevisedTimeServer", targetNamespace = "http://ch02.tsa", wsdlLocation = "http://localhost:9876/tsa?wsdl")
public class RevisedTimeServer
    extends Service
{

    private final static URL REVISEDTIMESERVER_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://localhost:9876/tsa?wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        REVISEDTIMESERVER_WSDL_LOCATION = url;
    }

    public RevisedTimeServer(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RevisedTimeServer() {
        super(REVISEDTIMESERVER_WSDL_LOCATION, new QName("http://ch02.tsa", "RevisedTimeServer"));
    }

    /**
     * 
     * @return
     *     returns AnnotatedTimeServer
     */
    @WebEndpoint(name = "AnnotatedTimeServerPort")
    public AnnotatedTimeServer getAnnotatedTimeServerPort() {
        return (AnnotatedTimeServer)super.getPort(new QName("http://ch02.tsa", "AnnotatedTimeServerPort"), AnnotatedTimeServer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AnnotatedTimeServer
     */
    @WebEndpoint(name = "AnnotatedTimeServerPort")
    public AnnotatedTimeServer getAnnotatedTimeServerPort(WebServiceFeature... features) {
        return (AnnotatedTimeServer)super.getPort(new QName("http://ch02.tsa", "AnnotatedTimeServerPort"), AnnotatedTimeServer.class, features);
    }

}
