rem %1% the string you're looking for
del findSql.txt
find /i /c "%1%" 037.sql >> findSql.txt
find /i /c "%1%" 040.sql >> findSql.txt
find /i /c "%1%" 060.sql >> findSql.txt
find /i /c "%1%" 053.sql >> findSql.txt
find /i /c "%1%" 065.sql >> findSql.txt
find /i /c "%1%" 039.sql >> findSql.txt
find /i /c "%1%" 089.sql >> findSql.txt
find /i /c "%1%" 105.sql >> findSql.txt
find /i /c "%1%" 106.sql >> findSql.txt
find /i /c "%1%" 117.sql >> findSql.txt
find /i /c "%1%" 035.sql >> findSql.txt
find /i /c "%1%" 105a.sql >> findSql.txt
find /i /c "%1%" 108.sql >> findSql.txt
find /i /c "%1%" 108b.sql >> findSql.txt
find /i /c "%1%" 108c.sql >> findSql.txt
find /i /c "%1%" 111.sql >> findSql.txt
find /i /c "%1%" 113.sql >> findSql.txt
find /i /c "%1%" golf.sql >> findSql.txt
find /i /c "%1%" 119.sql >> findSql.txt
find /i /c "%1%" 88a.sql >> findSql.txt
find /i /c "%1%" 141.sql >> findSql.txt
find /i /c "%1%" 89a.sql >> findSql.txt
find /i /c "%1%" 103.sql >> findSql.txt
find /i /c "%1%" 108a.sql >> findSql.txt
find /i /c "%1%" 111a.sql >> findSql.txt
find /i /c "%1%" 114.sql >> findSql.txt
find /i /c "%1%" 117a.sql >> findSql.txt
find /i /c "%1%" 123.sql >> findSql.txt
find /i /c "%1%" 123a.sql >> findSql.txt
find /i /c "%1%" 137.sql >> findSql.txt
find /i /c "%1%" 114a.sql >> findSql.txt
find /i /c "%1%" 114b.sql >> findSql.txt
find /i /c "%1%" 114c.sql >> findSql.txt
find /i /c "%1%" 116.sql >> findSql.txt
find /i /c "%1%" 116a.sql >> findSql.txt
find /i /c "%1%" 122.sql >> findSql.txt
find /i /c "%1%" 124.sql >> findSql.txt
find /i /c "%1%" 191.sql >> findSql.txt
find /i /c "%1%" 215.SQL >> findSql.txt
find /i /c "%1%" 211.sql >> findSql.txt
find /i /c "%1%" 218.sql >> findSql.txt
find /i /c "%1%" 218a.sql >> findSql.txt
find /i /c "%1%" 177.sql >> findSql.txt
find /i /c "%1%" 218b.sql >> findSql.txt
find /i /c "%1%" 189.sql >> findSql.txt
find /i /c "%1%" 197.sql >> findSql.txt
find /i /c "%1%" 216.sql >> findSql.txt
find /i /c "%1%" 248.sql >> findSql.txt
find /i /c "%1%" 252b.sql >> findSql.txt
find /i /c "%1%" 252a.sql >> findSql.txt
find /i /c "%1%" 254.sql >> findSql.txt
find /i /c "%1%" 255.sql >> findSql.txt
find /i /c "%1%" 253.sql >> findSql.txt
find /i /c "%1%" 257.sql >> findSql.txt
find /i /c "%1%" 257b.sql >> findSql.txt
find /i /c "%1%" 257c.sql >> findSql.txt
find /i /c "%1%" 258.sql >> findSql.txt
find /i /c "%1%" 263.sql >> findSql.txt
find /i /c "%1%" 284.sql >> findSql.txt
find /i /c "%1%" 285.sql >> findSql.txt
find /i /c "%1%" 248b.sql >> findSql.txt
find /i /c "%1%" 320.sql >> findSql.txt
find /i /c "%1%" 252c.sql >> findSql.txt
find /i /c "%1%" 321.sql >> findSql.txt
find /i /c "%1%" 324.sql >> findSql.txt
find /i /c "%1%" 324b.sql >> findSql.txt
find /i /c "%1%" 330.sql >> findSql.txt
find /i /c "%1%" myblock.sql >> findSql.txt
find /i /c "%1%" 343.sql >> findSql.txt
find /i /c "%1%" 343b.sql >> findSql.txt
find /i /c "%1%" 344.sql >> findSql.txt
find /i /c "%1%" 356.sql >> findSql.txt
find /i /c "%1%" 356a.sql >> findSql.txt
find /i /c "%1%" 357.sql >> findSql.txt
find /i /c "%1%" 357b.sql >> findSql.txt
find /i /c "%1%" 357c.sql >> findSql.txt
find /i /c "%1%" 358.sql >> findSql.txt
find /i /c "%1%" 362.sql >> findSql.txt
find /i /c "%1%" 365.sql >> findSql.txt
find /i /c "%1%" 364.sql >> findSql.txt
find /i /c "%1%" 376.sql >> findSql.txt
find /i /c "%1%" 376b.sql >> findSql.txt
find /i /c "%1%" login.sql >> findSql.txt
find /i /c "%1%" 378.sql >> findSql.txt
find /i /c "%1%" 380.sql >> findSql.txt
find /i /c "%1%" 380b.sql >> findSql.txt
find /i /c "%1%" 380c.sql >> findSql.txt
find /i /c "%1%" 382.sql >> findSql.txt
find /i /c "%1%" 383.sql >> findSql.txt
find /i /c "%1%" 383b.sql >> findSql.txt
find /i /c "%1%" 383c.sql >> findSql.txt
find /i /c "%1%" 386.sql >> findSql.txt
find /i /c "%1%" 386b.sql >> findSql.txt
find /i /c "%1%" 390.sql >> findSql.txt
find /i /c "%1%" 390b.sql >> findSql.txt
find /i /c "%1%" 394.sql >> findSql.txt
find /i /c "%1%" 395.sql >> findSql.txt
find /i /c "%1%" 396.sql >> findSql.txt
find /i /c "%1%" 395b.sql >> findSql.txt
find /i /c "%1%" 396b.sql >> findSql.txt
find /i /c "%1%" 398.sql >> findSql.txt
find /i /c "%1%" 398b.sql >> findSql.txt
find /i /c "%1%" 401.sql >> findSql.txt
find /i /c "%1%" 402.sql >> findSql.txt
find /i /c "%1%" 402b.sql >> findSql.txt
find /i /c "%1%" 403.sql >> findSql.txt
find /i /c "%1%" nested_tables.sql >> findSql.txt
find /i /c "%1%" 405.sql >> findSql.txt
find /i /c "%1%" 406.sql >> findSql.txt
find /i /c "%1%" 406b.sql >> findSql.txt
find /i /c "%1%" 407.sql >> findSql.txt
find /i /c "%1%" 407b.sql >> findSql.txt
find /i /c "%1%" 410.sql >> findSql.txt
find /i /c "%1%" 421.sql >> findSql.txt
find /i /c "%1%" 421b.sql >> findSql.txt
find /i /c "%1%" 412.sql >> findSql.txt
find /i /c "%1%" 412b.sql >> findSql.txt
find /i /c "%1%" 412d.sql >> findSql.txt
find /i /c "%1%" 412c.sql >> findSql.txt
find /i /c "%1%" 413.sql >> findSql.txt
find /i /c "%1%" 413b.sql >> findSql.txt
find /i /c "%1%" 413c.sql >> findSql.txt
find /i /c "%1%" 413d.sql >> findSql.txt
find /i /c "%1%" 418.sql >> findSql.txt
find /i /c "%1%" 418b.sql >> findSql.txt
find /i /c "%1%" 418c.sql >> findSql.txt
find /i /c "%1%" 418d.sql >> findSql.txt
find /i /c "%1%" 419.sql >> findSql.txt
find /i /c "%1%" 419b.sql >> findSql.txt
find /i /c "%1%" 419c.sql >> findSql.txt
find /i /c "%1%" 419d.sql >> findSql.txt
find /i /c "%1%" 422.sql >> findSql.txt
find /i /c "%1%" 424.sql >> findSql.txt
find /i /c "%1%" 422b.sql >> findSql.txt
find /i /c "%1%" 424b.sql >> findSql.txt
find /i /c "%1%" 427.sql >> findSql.txt
find /i /c "%1%" 428.sql >> findSql.txt
find /i /c "%1%" 429.sql >> findSql.txt
find /i /c "%1%" 429b.sql >> findSql.txt
find /i /c "%1%" 430.sql >> findSql.txt
find /i /c "%1%" 430b.sql >> findSql.txt
find /i /c "%1%" 431.sql >> findSql.txt
find /i /c "%1%" 431b.sql >> findSql.txt
find /i /c "%1%" 433.sql >> findSql.txt
find /i /c "%1%" 433b.sql >> findSql.txt
find /i /c "%1%" 434.sql >> findSql.txt
find /i /c "%1%" 434b.sql >> findSql.txt
find /i /c "%1%" 438.sql >> findSql.txt
find /i /c "%1%" 437.sql >> findSql.txt
find /i /c "%1%" 437b.sql >> findSql.txt
find /i /c "%1%" 438b.sql >> findSql.txt
find /i /c "%1%" 442.sql >> findSql.txt
find /i /c "%1%" 438c.sql >> findSql.txt
find /i /c "%1%" 436.sql >> findSql.txt
find /i /c "%1%" 442b.sql >> findSql.txt
find /i /c "%1%" 427b.sql >> findSql.txt
find /i /c "%1%" 028.sql >> findSql.txt
find /i /c "%1%" 029.sql >> findSql.txt
find /i /c "%1%" 048.sql >> findSql.txt
find /i /c "%1%" 050.sql >> findSql.txt
find /i /c "%1%" 051.sql >> findSql.txt
find /i /c "%1%" 062.sql >> findSql.txt
find /i /c "%1%" 119b.sql >> findSql.txt
find /i /c "%1%" 119c.sql >> findSql.txt
find /i /c "%1%" 117d.sql >> findSql.txt
find /i /c "%1%" 120.sql >> findSql.txt
find /i /c "%1%" 125.sql >> findSql.txt
find /i /c "%1%" 127.sql >> findSql.txt
find /i /c "%1%" 127b.sql >> findSql.txt
find /i /c "%1%" 218c.sql >> findSql.txt
find /i /c "%1%" 254b.sql >> findSql.txt
find /i /c "%1%" 403b.sql >> findSql.txt
find /i /c "%1%" 331.sql >> findSql.txt
find /i /c "%1%" 334.sql >> findSql.txt
find /i /c "%1%" 334b.sql >> findSql.txt
find /i /c "%1%" 334c.sql >> findSql.txt
find /i /c "%1%" 382b.sql >> findSql.txt
find /i /c "%1%" 337.sql >> findSql.txt
find /i /c "%1%" 394b.sql >> findSql.txt
find /i /c "%1%" cons_columns.sql >> findSql.txt
find /i /c "%1%" col_constraints.sql >> findSql.txt
find /i /c "%1%" 399.sql >> findSql.txt
find /i /c "%1%" 406c.sql >> findSql.txt
find /i /c "%1%" null_cursors.sql >> findSql.txt
find /i /c "%1%" golf2.sql >> findSql.txt
find /i /c "%1%" objects.sql >> findSql.txt
find /i /c "%1%" 441.sql >> findSql.txt
find /i /c "%1%" labeled_loop.sql >> findSql.txt
find /i /c "%1%" 441b.sql >> findSql.txt
find /i /c "%1%" 441c.sql >> findSql.txt
find /i /c "%1%" before_trigger.sql >> findSql.txt
find /i /c "%1%" after_trigger.sql >> findSql.txt
find /i /c "%1%" instead_of_trigger.sql >> findSql.txt
find /i /c "%1%" servererror_trigger.sql >> findSql.txt
find /i /c "%1%" logon_trigger.sql >> findSql.txt
find /i /c "%1%" row_level_trigger.sql >> findSql.txt
find /i /c "%1%" predicates_trigger.sql >> findSql.txt
find /i /c "%1%" cursor_type.sql >> findSql.txt
find /i /c "%1%" cursor_type2.sql >> findSql.txt
find /i /c "%1%" cursor_binary_table.sql >> findSql.txt
find /i /c "%1%" implicit_cursors.sql >> findSql.txt
lemmy findSql.txt
