del golf1.txt
find /i /c "create" 037.sql >> golf1.txt
find /i /c "create" 040.sql >> golf1.txt
find /i /c "create" 060.sql >> golf1.txt
find /i /c "create" 053.sql >> golf1.txt
find /i /c "create" 065.sql >> golf1.txt
find /i /c "create" 039.sql >> golf1.txt
find /i /c "create" 089.sql >> golf1.txt
find /i /c "create" 105.sql >> golf1.txt
find /i /c "create" 106.sql >> golf1.txt
find /i /c "create" 117.sql >> golf1.txt
find /i /c "create" 035.sql >> golf1.txt
find /i /c "create" 105a.sql >> golf1.txt
find /i /c "create" 108.sql >> golf1.txt
find /i /c "create" 108b.sql >> golf1.txt
find /i /c "create" 108c.sql >> golf1.txt
find /i /c "create" 111.sql >> golf1.txt
find /i /c "create" 113.sql >> golf1.txt
find /i /c "create" golf.sql >> golf1.txt
find /i /c "create" 119.sql >> golf1.txt
find /i /c "create" 88a.sql >> golf1.txt
find /i /c "create" 141.sql >> golf1.txt
find /i /c "create" 89a.sql >> golf1.txt
find /i /c "create" 103.sql >> golf1.txt
find /i /c "create" 108a.sql >> golf1.txt
find /i /c "create" 111a.sql >> golf1.txt
find /i /c "create" 114.sql >> golf1.txt
find /i /c "create" 117a.sql >> golf1.txt
find /i /c "create" 123.sql >> golf1.txt
find /i /c "create" 123a.sql >> golf1.txt
find /i /c "create" 137.sql >> golf1.txt
find /i /c "create" 114a.sql >> golf1.txt
find /i /c "create" 114b.sql >> golf1.txt
find /i /c "create" 114c.sql >> golf1.txt
find /i /c "create" 116.sql >> golf1.txt
find /i /c "create" 116a.sql >> golf1.txt
find /i /c "create" 122.sql >> golf1.txt
find /i /c "create" 124.sql >> golf1.txt
find /i /c "create" 191.sql >> golf1.txt
find /i /c "create" 215.SQL >> golf1.txt
find /i /c "create" 211.sql >> golf1.txt
find /i /c "create" 218.sql >> golf1.txt
find /i /c "create" 218a.sql >> golf1.txt
find /i /c "create" 177.sql >> golf1.txt
find /i /c "create" 218b.sql >> golf1.txt
find /i /c "create" 189.sql >> golf1.txt
find /i /c "create" 197.sql >> golf1.txt
find /i /c "create" 216.sql >> golf1.txt
find /i /c "create" 248.sql >> golf1.txt
find /i /c "create" 252b.sql >> golf1.txt
find /i /c "create" 252a.sql >> golf1.txt
find /i /c "create" 254.sql >> golf1.txt
find /i /c "create" 255.sql >> golf1.txt
find /i /c "create" 253.sql >> golf1.txt
find /i /c "create" 257.sql >> golf1.txt
find /i /c "create" 257b.sql >> golf1.txt
find /i /c "create" 257c.sql >> golf1.txt
find /i /c "create" 258.sql >> golf1.txt
find /i /c "create" 263.sql >> golf1.txt
find /i /c "create" 284.sql >> golf1.txt
find /i /c "create" 285.sql >> golf1.txt
find /i /c "create" 248b.sql >> golf1.txt
find /i /c "create" 320.sql >> golf1.txt
find /i /c "create" 252c.sql >> golf1.txt
find /i /c "create" 321.sql >> golf1.txt
find /i /c "create" 324.sql >> golf1.txt
find /i /c "create" 324b.sql >> golf1.txt
find /i /c "create" 330.sql >> golf1.txt
find /i /c "create" myblock.sql >> golf1.txt
find /i /c "create" 343.sql >> golf1.txt
find /i /c "create" 343b.sql >> golf1.txt
find /i /c "create" 344.sql >> golf1.txt
find /i /c "create" 356.sql >> golf1.txt
find /i /c "create" 356a.sql >> golf1.txt
find /i /c "create" 357.sql >> golf1.txt
find /i /c "create" 357b.sql >> golf1.txt
find /i /c "create" 357c.sql >> golf1.txt
find /i /c "create" 358.sql >> golf1.txt
find /i /c "create" 362.sql >> golf1.txt
find /i /c "create" 365.sql >> golf1.txt
find /i /c "create" 364.sql >> golf1.txt
find /i /c "create" 376.sql >> golf1.txt
find /i /c "create" 376b.sql >> golf1.txt
find /i /c "create" login.sql >> golf1.txt
find /i /c "create" 378.sql >> golf1.txt
find /i /c "create" 380.sql >> golf1.txt
find /i /c "create" 380b.sql >> golf1.txt
find /i /c "create" 380c.sql >> golf1.txt
find /i /c "create" 382.sql >> golf1.txt
find /i /c "create" 383.sql >> golf1.txt
find /i /c "create" 383b.sql >> golf1.txt
find /i /c "create" 383c.sql >> golf1.txt
find /i /c "create" 386.sql >> golf1.txt
find /i /c "create" 386b.sql >> golf1.txt
find /i /c "create" 390.sql >> golf1.txt
find /i /c "create" 390b.sql >> golf1.txt
find /i /c "create" 394.sql >> golf1.txt
find /i /c "create" 395.sql >> golf1.txt
find /i /c "create" 396.sql >> golf1.txt
find /i /c "create" 395b.sql >> golf1.txt
find /i /c "create" 396b.sql >> golf1.txt
find /i /c "create" 398.sql >> golf1.txt
find /i /c "create" 398b.sql >> golf1.txt
find /i /c "create" 401.sql >> golf1.txt
find /i /c "create" 402.sql >> golf1.txt
find /i /c "create" 402b.sql >> golf1.txt
find /i /c "create" 403.sql >> golf1.txt
find /i /c "create" nested_tables.sql >> golf1.txt
find /i /c "create" 405.sql >> golf1.txt
find /i /c "create" 406.sql >> golf1.txt
find /i /c "create" 406b.sql >> golf1.txt
find /i /c "create" 407.sql >> golf1.txt
find /i /c "create" 407b.sql >> golf1.txt
find /i /c "create" 410.sql >> golf1.txt
find /i /c "create" 421.sql >> golf1.txt
find /i /c "create" 421b.sql >> golf1.txt
find /i /c "create" 412.sql >> golf1.txt
find /i /c "create" 412b.sql >> golf1.txt
find /i /c "create" 412d.sql >> golf1.txt
find /i /c "create" 412c.sql >> golf1.txt
find /i /c "create" 413.sql >> golf1.txt
find /i /c "create" 413b.sql >> golf1.txt
find /i /c "create" 413c.sql >> golf1.txt
find /i /c "create" 413d.sql >> golf1.txt
find /i /c "create" 418.sql >> golf1.txt
find /i /c "create" 418b.sql >> golf1.txt
find /i /c "create" 418c.sql >> golf1.txt
find /i /c "create" 418d.sql >> golf1.txt
find /i /c "create" 419.sql >> golf1.txt
find /i /c "create" 419b.sql >> golf1.txt
find /i /c "create" 419c.sql >> golf1.txt
find /i /c "create" 419d.sql >> golf1.txt
find /i /c "create" 422.sql >> golf1.txt
find /i /c "create" 424.sql >> golf1.txt
find /i /c "create" 422b.sql >> golf1.txt
find /i /c "create" 424b.sql >> golf1.txt
find /i /c "create" 427.sql >> golf1.txt
find /i /c "create" 428.sql >> golf1.txt
find /i /c "create" 429.sql >> golf1.txt
find /i /c "create" 429b.sql >> golf1.txt
find /i /c "create" 430.sql >> golf1.txt
find /i /c "create" 430b.sql >> golf1.txt
find /i /c "create" 431.sql >> golf1.txt
find /i /c "create" 431b.sql >> golf1.txt
find /i /c "create" 433.sql >> golf1.txt
find /i /c "create" 433b.sql >> golf1.txt
find /i /c "create" 434.sql >> golf1.txt
find /i /c "create" 434b.sql >> golf1.txt
find /i /c "create" 438.sql >> golf1.txt
find /i /c "create" 437.sql >> golf1.txt
find /i /c "create" 437b.sql >> golf1.txt
find /i /c "create" 438b.sql >> golf1.txt
find /i /c "create" 442.sql >> golf1.txt
find /i /c "create" 438c.sql >> golf1.txt
find /i /c "create" 436.sql >> golf1.txt
find /i /c "create" 442b.sql >> golf1.txt
find /i /c "create" 427b.sql >> golf1.txt
find /i /c "create" 028.sql >> golf1.txt
find /i /c "create" 029.sql >> golf1.txt
find /i /c "create" 048.sql >> golf1.txt
find /i /c "create" 050.sql >> golf1.txt
find /i /c "create" 051.sql >> golf1.txt
find /i /c "create" 062.sql >> golf1.txt
find /i /c "create" 119b.sql >> golf1.txt
find /i /c "create" 119c.sql >> golf1.txt
find /i /c "create" 117d.sql >> golf1.txt
find /i /c "create" 120.sql >> golf1.txt
find /i /c "create" 125.sql >> golf1.txt
find /i /c "create" 127.sql >> golf1.txt
find /i /c "create" 127b.sql >> golf1.txt
find /i /c "create" 218c.sql >> golf1.txt
find /i /c "create" 254b.sql >> golf1.txt
find /i /c "create" 403b.sql >> golf1.txt
find /i /c "create" 331.sql >> golf1.txt
find /i /c "create" 334.sql >> golf1.txt
find /i /c "create" 334b.sql >> golf1.txt
find /i /c "create" 334c.sql >> golf1.txt
find /i /c "create" 382b.sql >> golf1.txt
find /i /c "create" 337.sql >> golf1.txt
find /i /c "create" 394b.sql >> golf1.txt
find /i /c "create" cons_columns.sql >> golf1.txt
find /i /c "create" col_constraints.sql >> golf1.txt
find /i /c "create" 399.sql >> golf1.txt
find /i /c "create" 406c.sql >> golf1.txt
find /i /c "create" null_cursors.sql >> golf1.txt
find /i /c "create" golf2.sql >> golf1.txt
find /i /c "create" objects.sql >> golf1.txt
find /i /c "create" 441.sql >> golf1.txt
find /i /c "create" labeled_loop.sql >> golf1.txt
find /i /c "create" 441b.sql >> golf1.txt
find /i /c "create" 441c.sql >> golf1.txt
find /i /c "create" before_trigger.sql >> golf1.txt
find /i /c "create" after_trigger.sql >> golf1.txt
find /i /c "create" instead_of_trigger.sql >> golf1.txt
find /i /c "create" servererror_trigger.sql >> golf1.txt
find /i /c "create" logon_trigger.sql >> golf1.txt
find /i /c "create" row_level_trigger.sql >> golf1.txt
find /i /c "create" predicates_trigger.sql >> golf1.txt
find /i /c "create" cursor_type.sql >> golf1.txt
find /i /c "create" cursor_type2.sql >> golf1.txt
find /i /c "create" cursor_binary_table.sql >> golf1.txt
find /i /c "create" implicit_cursors.sql >> golf1.txt
