
package fibC;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.jws.HandlerChain; // added

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "RabbitCounterService", 
                  targetNamespace = "http://ch03.fib", 
                  wsdlLocation = "http://localhost:8888/fib?wsdl")
@HandlerChain(file = "handler-chain.xml") // added
public class RabbitCounterService
    extends Service
{

    private final static URL RABBITCOUNTERSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8888/fib?wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        RABBITCOUNTERSERVICE_WSDL_LOCATION = url;
    }

    public RabbitCounterService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RabbitCounterService() {
        super(RABBITCOUNTERSERVICE_WSDL_LOCATION, new QName("http://ch03.fib", "RabbitCounterService"));
    }

    /**
     * 
     * @return
     *     returns RabbitCounter
     */
    @WebEndpoint(name = "RabbitCounterPort")
    public RabbitCounter getRabbitCounterPort() {
        return (RabbitCounter)super.getPort(new QName("http://ch03.fib", "RabbitCounterPort"), RabbitCounter.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RabbitCounter
     */
    @WebEndpoint(name = "RabbitCounterPort")
    public RabbitCounter getRabbitCounterPort(WebServiceFeature... features) {
        return (RabbitCounter)super.getPort(new QName("http://ch03.fib", "RabbitCounterPort"), RabbitCounter.class, features);
    }

}
