
package tcClient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "TempConvertImplService", targetNamespace = "http://tc.ch05/", wsdlLocation = "http://localhost:8080/tempc/tc?wsdl")
public class TempConvertImplService
    extends Service
{

    private final static URL TEMPCONVERTIMPLSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/tempc/tc?wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        TEMPCONVERTIMPLSERVICE_WSDL_LOCATION = url;
    }

    public TempConvertImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TempConvertImplService() {
        super(TEMPCONVERTIMPLSERVICE_WSDL_LOCATION, new QName("http://tc.ch05/", "TempConvertImplService"));
    }

    /**
     * 
     * @return
     *     returns TempConvert
     */
    @WebEndpoint(name = "TempConvertImplPort")
    public TempConvert getTempConvertImplPort() {
        return (TempConvert)super.getPort(new QName("http://tc.ch05/", "TempConvertImplPort"), TempConvert.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TempConvert
     */
    @WebEndpoint(name = "TempConvertImplPort")
    public TempConvert getTempConvertImplPort(WebServiceFeature... features) {
        return (TempConvert)super.getPort(new QName("http://tc.ch05/", "TempConvertImplPort"), TempConvert.class, features);
    }

}
