
package skiC2;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "SkiImageService", targetNamespace = "http://image.ch03/", wsdlLocation = "file:/home/kalin/jwsur_code/chapter3/ch03/image/ski.wsdl")
public class SkiImageService_Service
    extends Service
{

    private final static URL SKIIMAGESERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("file:/home/kalin/jwsur_code/chapter3/ch03/image/ski.wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        SKIIMAGESERVICE_WSDL_LOCATION = url;
    }

    public SkiImageService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SkiImageService_Service() {
        super(SKIIMAGESERVICE_WSDL_LOCATION, new QName("http://image.ch03/", "SkiImageService"));
    }

    /**
     * 
     * @return
     *     returns SkiImageService
     */
    @WebEndpoint(name = "SkiImageServicePort")
    public SkiImageService getSkiImageServicePort() {
        return (SkiImageService)super.getPort(new QName("http://image.ch03/", "SkiImageServicePort"), SkiImageService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SkiImageService
     */
    @WebEndpoint(name = "SkiImageServicePort")
    public SkiImageService getSkiImageServicePort(WebServiceFeature... features) {
        return (SkiImageService)super.getPort(new QName("http://image.ch03/", "SkiImageServicePort"), SkiImageService.class, features);
    }

}
