
package awsClient2;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import awsClient.MultiOperation;
import awsClient.MultiOperationResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "AWSECommerceServicePortType", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AWSECommerceServicePortType {


    /**
     * 
     * @param body
     * @return
     *     returns awsClient2.HelpResponse
     */
    @WebMethod(operationName = "Help", action = "http://soap.amazon.com")
    @WebResult(name = "HelpResponse", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
    public HelpResponse help(
        @WebParam(name = "Help", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
        Help body);

    /**
     * 
     * @param body
     * @return
     *     returns awsClient2.ItemSearchResponse
     */
    @WebMethod(operationName = "ItemSearch", action = "http://soap.amazon.com")
    @WebResult(name = "ItemSearchResponse", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
    public ItemSearchResponse itemSearch(
        @WebParam(name = "ItemSearch", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
        ItemSearch body);

    /**
     * 
     * @param body
     * @return
     *     returns awsClient2.ItemLookupResponse
     */
    @WebMethod(operationName = "ItemLookup", action = "http://soap.amazon.com")
    @WebResult(name = "ItemLookupResponse", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
    public ItemLookupResponse itemLookup(
        @WebParam(name = "ItemLookup", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
        ItemLookup body);

    /**
     * 
     * @param body
     * @return
     *     returns awsClient2.BrowseNodeLookupResponse
     */
    @WebMethod(operationName = "BrowseNodeLookup", action = "http://soap.amazon.com")
    @WebResult(name = "BrowseNodeLookupResponse", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
    public BrowseNodeLookupResponse browseNodeLookup(
        @WebParam(name = "BrowseNodeLookup", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
        BrowseNodeLookup body);

    /**
     * 
     * @param body
     * @return
     *     returns awsClient2.ListSearchResponse
     */
    @WebMethod(operationName = "ListSearch", action = "http://soap.amazon.com")
    @WebResult(name = "ListSearchResponse", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
    public ListSearchResponse listSearch(
        @WebParam(name = "ListSearch", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
        ListSearch body);

    /**
     * 
     * @param body
     * @return
     *     returns awsClient2.ListLookupResponse
     */
    @WebMethod(operationName = "ListLookup", action = "http://soap.amazon.com")
    @WebResult(name = "ListLookupResponse", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
    public ListLookupResponse listLookup(
        @WebParam(name = "ListLookup", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
        ListLookup body);

    /**
     * 
     * @param body
     * @return
     *     returns awsClient2.CustomerContentSearchResponse
     */
    @WebMethod(operationName = "CustomerContentSearch", action = "http://soap.amazon.com")
    @WebResult(name = "CustomerContentSearchResponse", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
    public CustomerContentSearchResponse customerContentSearch(
        @WebParam(name = "CustomerContentSearch", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
        CustomerContentSearch body);

    /**
     * 
     * @param body
     * @return
     *     returns awsClient2.CustomerContentLookupResponse
     */
    @WebMethod(operationName = "CustomerContentLookup", action = "http://soap.amazon.com")
    @WebResult(name = "CustomerContentLookupResponse", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
    public CustomerContentLookupResponse customerContentLookup(
        @WebParam(name = "CustomerContentLookup", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
        CustomerContentLookup body);

    /**
     * 
     * @param body
     * @return
     *     returns awsClient2.SimilarityLookupResponse
     */
    @WebMethod(operationName = "SimilarityLookup", action = "http://soap.amazon.com")
    @WebResult(name = "SimilarityLookupResponse", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
    public SimilarityLookupResponse similarityLookup(
        @WebParam(name = "SimilarityLookup", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
        SimilarityLookup body);

    /**
     * 
     * @param body
     * @return
     *     returns awsClient2.SellerLookupResponse
     */
    @WebMethod(operationName = "SellerLookup", action = "http://soap.amazon.com")
    @WebResult(name = "SellerLookupResponse", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
    public SellerLookupResponse sellerLookup(
        @WebParam(name = "SellerLookup", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
        SellerLookup body);

    /**
     * 
     * @param body
     * @return
     *     returns awsClient2.CartGetResponse
     */
    @WebMethod(operationName = "CartGet", action = "http://soap.amazon.com")
    @WebResult(name = "CartGetResponse", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
    public CartGetResponse cartGet(
        @WebParam(name = "CartGet", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
        CartGet body);

    /**
     * 
     * @param body
     * @return
     *     returns awsClient2.CartCreateResponse
     */
    @WebMethod(operationName = "CartCreate", action = "http://soap.amazon.com")
    @WebResult(name = "CartCreateResponse", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
    public CartCreateResponse cartCreate(
        @WebParam(name = "CartCreate", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
        CartCreate body);

    /**
     * 
     * @param body
     * @return
     *     returns awsClient2.CartAddResponse
     */
    @WebMethod(operationName = "CartAdd", action = "http://soap.amazon.com")
    @WebResult(name = "CartAddResponse", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
    public CartAddResponse cartAdd(
        @WebParam(name = "CartAdd", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
        CartAdd body);

    /**
     * 
     * @param body
     * @return
     *     returns awsClient2.CartModifyResponse
     */
    @WebMethod(operationName = "CartModify", action = "http://soap.amazon.com")
    @WebResult(name = "CartModifyResponse", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
    public CartModifyResponse cartModify(
        @WebParam(name = "CartModify", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
        CartModify body);

    /**
     * 
     * @param body
     * @return
     *     returns awsClient2.CartClearResponse
     */
    @WebMethod(operationName = "CartClear", action = "http://soap.amazon.com")
    @WebResult(name = "CartClearResponse", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
    public CartClearResponse cartClear(
        @WebParam(name = "CartClear", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
        CartClear body);

    /**
     * 
     * @param body
     * @return
     *     returns awsClient2.TransactionLookupResponse
     */
    @WebMethod(operationName = "TransactionLookup", action = "http://soap.amazon.com")
    @WebResult(name = "TransactionLookupResponse", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
    public TransactionLookupResponse transactionLookup(
        @WebParam(name = "TransactionLookup", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
        TransactionLookup body);

    /**
     * 
     * @param body
     * @return
     *     returns awsClient2.SellerListingSearchResponse
     */
    @WebMethod(operationName = "SellerListingSearch", action = "http://soap.amazon.com")
    @WebResult(name = "SellerListingSearchResponse", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
    public SellerListingSearchResponse sellerListingSearch(
        @WebParam(name = "SellerListingSearch", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
        SellerListingSearch body);

    /**
     * 
     * @param body
     * @return
     *     returns awsClient2.SellerListingLookupResponse
     */
    @WebMethod(operationName = "SellerListingLookup", action = "http://soap.amazon.com")
    @WebResult(name = "SellerListingLookupResponse", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
    public SellerListingLookupResponse sellerListingLookup(
        @WebParam(name = "SellerListingLookup", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
        SellerListingLookup body);

    /**
     * 
     * @param body
     * @return
     *     returns awsClient2.TagLookupResponse
     */
    @WebMethod(operationName = "TagLookup", action = "http://soap.amazon.com")
    @WebResult(name = "TagLookupResponse", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
    public TagLookupResponse tagLookup(
        @WebParam(name = "TagLookup", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
        TagLookup body);

    /**
     * 
     * @param body
     * @return
     *     returns awsClient2.VehicleSearchResponse
     */
    @WebMethod(operationName = "VehicleSearch", action = "http://soap.amazon.com")
    @WebResult(name = "VehicleSearchResponse", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
    public VehicleSearchResponse vehicleSearch(
        @WebParam(name = "VehicleSearch", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
        VehicleSearch body);

    /**
     * 
     * @param body
     * @return
     *     returns awsClient2.VehiclePartSearchResponse
     */
    @WebMethod(operationName = "VehiclePartSearch", action = "http://soap.amazon.com")
    @WebResult(name = "VehiclePartSearchResponse", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
    public VehiclePartSearchResponse vehiclePartSearch(
        @WebParam(name = "VehiclePartSearch", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
        VehiclePartSearch body);

    /**
     * 
     * @param body
     * @return
     *     returns awsClient2.VehiclePartLookupResponse
     */
    @WebMethod(operationName = "VehiclePartLookup", action = "http://soap.amazon.com")
    @WebResult(name = "VehiclePartLookupResponse", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
    public VehiclePartLookupResponse vehiclePartLookup(
        @WebParam(name = "VehiclePartLookup", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
        VehiclePartLookup body);

    /**
     * 
     * @param body
     * @return
     *     returns awsClient2.MultiOperationResponse
     */
    @WebMethod(operationName = "MultiOperation", action = "http://soap.amazon.com")
    @WebResult(name = "MultiOperationResponse", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
    public MultiOperationResponse multiOperation(
        @WebParam(name = "MultiOperation", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
        MultiOperation body);

}
