<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://pkg" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:impl="http://pkg" xmlns:intf="http://pkg" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<!--WSDL created by Apache Axis version: 1.4
Built on Apr 22, 2006 (06:55:48 PDT)-->

   <wsdl:portType name="MyService">

   </wsdl:portType>

   <wsdl:binding name="MyServiceSoapBinding" type="impl:MyService">

      <wsdlsoap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>

   </wsdl:binding>

   <wsdl:service name="MyServiceService">

      <wsdl:port binding="impl:MyServiceSoapBinding" name="MyService">

         <wsdlsoap:address location="http://localhost:8080/ResourceA/services/MyService"/>

      </wsdl:port>

   </wsdl:service>

</wsdl:definitions>
