
package awsClient3;

import java.util.concurrent.Future;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.AsyncHandler;
import javax.xml.ws.Response;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "AWSECommerceServicePortType", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AWSECommerceServicePortType {


    /**
     * 
     * @param body
     * @return
     *     returns javax.xml.ws.Response<awsClient3.HelpResponse>
     */
    @WebMethod(operationName = "Help", action = "http://soap.amazon.com")
    public Response<HelpResponse> helpAsync(
        @WebParam(name = "Help", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
        Help body);

    /**
     * 
     * @param body
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "Help", action = "http://soap.amazon.com")
    public Future<?> helpAsync(
        @WebParam(name = "Help", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
        Help body,
        @WebParam(name = "HelpResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<HelpResponse> asyncHandler);

    /**
     * 
     * @param body
     * @return
     *     returns awsClient3.HelpResponse
     */
    @WebMethod(operationName = "Help", action = "http://soap.amazon.com")
    @WebResult(name = "HelpResponse", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
    public HelpResponse help(
        @WebParam(name = "Help", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
        Help body);

    /**
     * 
     * @param body
     * @return
     *     returns javax.xml.ws.Response<awsClient3.ItemSearchResponse>
     */
    @WebMethod(operationName = "ItemSearch", action = "http://soap.amazon.com")
    public Response<ItemSearchResponse> itemSearchAsync(
        @WebParam(name = "ItemSearch", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
        ItemSearch body);

    /**
     * 
     * @param body
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "ItemSearch", action = "http://soap.amazon.com")
    public Future<?> itemSearchAsync(
        @WebParam(name = "ItemSearch", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
        ItemSearch body,
        @WebParam(name = "ItemSearchResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<ItemSearchResponse> asyncHandler);

    /**
     * 
     * @param body
     * @return
     *     returns awsClient3.ItemSearchResponse
     */
    @WebMethod(operationName = "ItemSearch", action = "http://soap.amazon.com")
    @WebResult(name = "ItemSearchResponse", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
    public ItemSearchResponse itemSearch(
        @WebParam(name = "ItemSearch", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
        ItemSearch body);

    /**
     * 
     * @param body
     * @return
     *     returns javax.xml.ws.Response<awsClient3.ItemLookupResponse>
     */
    @WebMethod(operationName = "ItemLookup", action = "http://soap.amazon.com")
    public Response<ItemLookupResponse> itemLookupAsync(
        @WebParam(name = "ItemLookup", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
        ItemLookup body);

    /**
     * 
     * @param body
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "ItemLookup", action = "http://soap.amazon.com")
    public Future<?> itemLookupAsync(
        @WebParam(name = "ItemLookup", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
        ItemLookup body,
        @WebParam(name = "ItemLookupResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<ItemLookupResponse> asyncHandler);

    /**
     * 
     * @param body
     * @return
     *     returns awsClient3.ItemLookupResponse
     */
    @WebMethod(operationName = "ItemLookup", action = "http://soap.amazon.com")
    @WebResult(name = "ItemLookupResponse", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
    public ItemLookupResponse itemLookup(
        @WebParam(name = "ItemLookup", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
        ItemLookup body);

    /**
     * 
     * @param body
     * @return
     *     returns javax.xml.ws.Response<awsClient3.BrowseNodeLookupResponse>
     */
    @WebMethod(operationName = "BrowseNodeLookup", action = "http://soap.amazon.com")
    public Response<BrowseNodeLookupResponse> browseNodeLookupAsync(
        @WebParam(name = "BrowseNodeLookup", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
        BrowseNodeLookup body);

    /**
     * 
     * @param body
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "BrowseNodeLookup", action = "http://soap.amazon.com")
    public Future<?> browseNodeLookupAsync(
        @WebParam(name = "BrowseNodeLookup", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
        BrowseNodeLookup body,
        @WebParam(name = "BrowseNodeLookupResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<BrowseNodeLookupResponse> asyncHandler);

    /**
     * 
     * @param body
     * @return
     *     returns awsClient3.BrowseNodeLookupResponse
     */
    @WebMethod(operationName = "BrowseNodeLookup", action = "http://soap.amazon.com")
    @WebResult(name = "BrowseNodeLookupResponse", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
    public BrowseNodeLookupResponse browseNodeLookup(
        @WebParam(name = "BrowseNodeLookup", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
        BrowseNodeLookup body);

    /**
     * 
     * @param body
     * @return
     *     returns javax.xml.ws.Response<awsClient3.ListSearchResponse>
     */
    @WebMethod(operationName = "ListSearch", action = "http://soap.amazon.com")
    public Response<ListSearchResponse> listSearchAsync(
        @WebParam(name = "ListSearch", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
        ListSearch body);

    /**
     * 
     * @param body
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "ListSearch", action = "http://soap.amazon.com")
    public Future<?> listSearchAsync(
        @WebParam(name = "ListSearch", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
        ListSearch body,
        @WebParam(name = "ListSearchResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<ListSearchResponse> asyncHandler);

    /**
     * 
     * @param body
     * @return
     *     returns awsClient3.ListSearchResponse
     */
    @WebMethod(operationName = "ListSearch", action = "http://soap.amazon.com")
    @WebResult(name = "ListSearchResponse", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
    public ListSearchResponse listSearch(
        @WebParam(name = "ListSearch", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
        ListSearch body);

    /**
     * 
     * @param body
     * @return
     *     returns javax.xml.ws.Response<awsClient3.ListLookupResponse>
     */
    @WebMethod(operationName = "ListLookup", action = "http://soap.amazon.com")
    public Response<ListLookupResponse> listLookupAsync(
        @WebParam(name = "ListLookup", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
        ListLookup body);

    /**
     * 
     * @param body
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "ListLookup", action = "http://soap.amazon.com")
    public Future<?> listLookupAsync(
        @WebParam(name = "ListLookup", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
        ListLookup body,
        @WebParam(name = "ListLookupResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<ListLookupResponse> asyncHandler);

    /**
     * 
     * @param body
     * @return
     *     returns awsClient3.ListLookupResponse
     */
    @WebMethod(operationName = "ListLookup", action = "http://soap.amazon.com")
    @WebResult(name = "ListLookupResponse", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
    public ListLookupResponse listLookup(
        @WebParam(name = "ListLookup", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
        ListLookup body);

    /**
     * 
     * @param body
     * @return
     *     returns javax.xml.ws.Response<awsClient3.CustomerContentSearchResponse>
     */
    @WebMethod(operationName = "CustomerContentSearch", action = "http://soap.amazon.com")
    public Response<CustomerContentSearchResponse> customerContentSearchAsync(
        @WebParam(name = "CustomerContentSearch", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
        CustomerContentSearch body);

    /**
     * 
     * @param body
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "CustomerContentSearch", action = "http://soap.amazon.com")
    public Future<?> customerContentSearchAsync(
        @WebParam(name = "CustomerContentSearch", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
        CustomerContentSearch body,
        @WebParam(name = "CustomerContentSearchResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<CustomerContentSearchResponse> asyncHandler);

    /**
     * 
     * @param body
     * @return
     *     returns awsClient3.CustomerContentSearchResponse
     */
    @WebMethod(operationName = "CustomerContentSearch", action = "http://soap.amazon.com")
    @WebResult(name = "CustomerContentSearchResponse", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
    public CustomerContentSearchResponse customerContentSearch(
        @WebParam(name = "CustomerContentSearch", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
        CustomerContentSearch body);

    /**
     * 
     * @param body
     * @return
     *     returns javax.xml.ws.Response<awsClient3.CustomerContentLookupResponse>
     */
    @WebMethod(operationName = "CustomerContentLookup", action = "http://soap.amazon.com")
    public Response<CustomerContentLookupResponse> customerContentLookupAsync(
        @WebParam(name = "CustomerContentLookup", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
        CustomerContentLookup body);

    /**
     * 
     * @param body
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "CustomerContentLookup", action = "http://soap.amazon.com")
    public Future<?> customerContentLookupAsync(
        @WebParam(name = "CustomerContentLookup", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
        CustomerContentLookup body,
        @WebParam(name = "CustomerContentLookupResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<CustomerContentLookupResponse> asyncHandler);

    /**
     * 
     * @param body
     * @return
     *     returns awsClient3.CustomerContentLookupResponse
     */
    @WebMethod(operationName = "CustomerContentLookup", action = "http://soap.amazon.com")
    @WebResult(name = "CustomerContentLookupResponse", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
    public CustomerContentLookupResponse customerContentLookup(
        @WebParam(name = "CustomerContentLookup", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
        CustomerContentLookup body);

    /**
     * 
     * @param body
     * @return
     *     returns javax.xml.ws.Response<awsClient3.SimilarityLookupResponse>
     */
    @WebMethod(operationName = "SimilarityLookup", action = "http://soap.amazon.com")
    public Response<SimilarityLookupResponse> similarityLookupAsync(
        @WebParam(name = "SimilarityLookup", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
        SimilarityLookup body);

    /**
     * 
     * @param body
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "SimilarityLookup", action = "http://soap.amazon.com")
    public Future<?> similarityLookupAsync(
        @WebParam(name = "SimilarityLookup", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
        SimilarityLookup body,
        @WebParam(name = "SimilarityLookupResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<SimilarityLookupResponse> asyncHandler);

    /**
     * 
     * @param body
     * @return
     *     returns awsClient3.SimilarityLookupResponse
     */
    @WebMethod(operationName = "SimilarityLookup", action = "http://soap.amazon.com")
    @WebResult(name = "SimilarityLookupResponse", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
    public SimilarityLookupResponse similarityLookup(
        @WebParam(name = "SimilarityLookup", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
        SimilarityLookup body);

    /**
     * 
     * @param body
     * @return
     *     returns javax.xml.ws.Response<awsClient3.SellerLookupResponse>
     */
    @WebMethod(operationName = "SellerLookup", action = "http://soap.amazon.com")
    public Response<SellerLookupResponse> sellerLookupAsync(
        @WebParam(name = "SellerLookup", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
        SellerLookup body);

    /**
     * 
     * @param body
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "SellerLookup", action = "http://soap.amazon.com")
    public Future<?> sellerLookupAsync(
        @WebParam(name = "SellerLookup", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
        SellerLookup body,
        @WebParam(name = "SellerLookupResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<SellerLookupResponse> asyncHandler);

    /**
     * 
     * @param body
     * @return
     *     returns awsClient3.SellerLookupResponse
     */
    @WebMethod(operationName = "SellerLookup", action = "http://soap.amazon.com")
    @WebResult(name = "SellerLookupResponse", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
    public SellerLookupResponse sellerLookup(
        @WebParam(name = "SellerLookup", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
        SellerLookup body);

    /**
     * 
     * @param body
     * @return
     *     returns javax.xml.ws.Response<awsClient3.CartGetResponse>
     */
    @WebMethod(operationName = "CartGet", action = "http://soap.amazon.com")
    public Response<CartGetResponse> cartGetAsync(
        @WebParam(name = "CartGet", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
        CartGet body);

    /**
     * 
     * @param body
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "CartGet", action = "http://soap.amazon.com")
    public Future<?> cartGetAsync(
        @WebParam(name = "CartGet", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
        CartGet body,
        @WebParam(name = "CartGetResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<CartGetResponse> asyncHandler);

    /**
     * 
     * @param body
     * @return
     *     returns awsClient3.CartGetResponse
     */
    @WebMethod(operationName = "CartGet", action = "http://soap.amazon.com")
    @WebResult(name = "CartGetResponse", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
    public CartGetResponse cartGet(
        @WebParam(name = "CartGet", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
        CartGet body);

    /**
     * 
     * @param body
     * @return
     *     returns javax.xml.ws.Response<awsClient3.CartCreateResponse>
     */
    @WebMethod(operationName = "CartCreate", action = "http://soap.amazon.com")
    public Response<CartCreateResponse> cartCreateAsync(
        @WebParam(name = "CartCreate", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
        CartCreate body);

    /**
     * 
     * @param body
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "CartCreate", action = "http://soap.amazon.com")
    public Future<?> cartCreateAsync(
        @WebParam(name = "CartCreate", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
        CartCreate body,
        @WebParam(name = "CartCreateResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<CartCreateResponse> asyncHandler);

    /**
     * 
     * @param body
     * @return
     *     returns awsClient3.CartCreateResponse
     */
    @WebMethod(operationName = "CartCreate", action = "http://soap.amazon.com")
    @WebResult(name = "CartCreateResponse", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
    public CartCreateResponse cartCreate(
        @WebParam(name = "CartCreate", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
        CartCreate body);

    /**
     * 
     * @param body
     * @return
     *     returns javax.xml.ws.Response<awsClient3.CartAddResponse>
     */
    @WebMethod(operationName = "CartAdd", action = "http://soap.amazon.com")
    public Response<CartAddResponse> cartAddAsync(
        @WebParam(name = "CartAdd", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
        CartAdd body);

    /**
     * 
     * @param body
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "CartAdd", action = "http://soap.amazon.com")
    public Future<?> cartAddAsync(
        @WebParam(name = "CartAdd", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
        CartAdd body,
        @WebParam(name = "CartAddResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<CartAddResponse> asyncHandler);

    /**
     * 
     * @param body
     * @return
     *     returns awsClient3.CartAddResponse
     */
    @WebMethod(operationName = "CartAdd", action = "http://soap.amazon.com")
    @WebResult(name = "CartAddResponse", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
    public CartAddResponse cartAdd(
        @WebParam(name = "CartAdd", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
        CartAdd body);

    /**
     * 
     * @param body
     * @return
     *     returns javax.xml.ws.Response<awsClient3.CartModifyResponse>
     */
    @WebMethod(operationName = "CartModify", action = "http://soap.amazon.com")
    public Response<CartModifyResponse> cartModifyAsync(
        @WebParam(name = "CartModify", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
        CartModify body);

    /**
     * 
     * @param body
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "CartModify", action = "http://soap.amazon.com")
    public Future<?> cartModifyAsync(
        @WebParam(name = "CartModify", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
        CartModify body,
        @WebParam(name = "CartModifyResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<CartModifyResponse> asyncHandler);

    /**
     * 
     * @param body
     * @return
     *     returns awsClient3.CartModifyResponse
     */
    @WebMethod(operationName = "CartModify", action = "http://soap.amazon.com")
    @WebResult(name = "CartModifyResponse", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
    public CartModifyResponse cartModify(
        @WebParam(name = "CartModify", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
        CartModify body);

    /**
     * 
     * @param body
     * @return
     *     returns javax.xml.ws.Response<awsClient3.CartClearResponse>
     */
    @WebMethod(operationName = "CartClear", action = "http://soap.amazon.com")
    public Response<CartClearResponse> cartClearAsync(
        @WebParam(name = "CartClear", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
        CartClear body);

    /**
     * 
     * @param body
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "CartClear", action = "http://soap.amazon.com")
    public Future<?> cartClearAsync(
        @WebParam(name = "CartClear", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
        CartClear body,
        @WebParam(name = "CartClearResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<CartClearResponse> asyncHandler);

    /**
     * 
     * @param body
     * @return
     *     returns awsClient3.CartClearResponse
     */
    @WebMethod(operationName = "CartClear", action = "http://soap.amazon.com")
    @WebResult(name = "CartClearResponse", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
    public CartClearResponse cartClear(
        @WebParam(name = "CartClear", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
        CartClear body);

    /**
     * 
     * @param body
     * @return
     *     returns javax.xml.ws.Response<awsClient3.TransactionLookupResponse>
     */
    @WebMethod(operationName = "TransactionLookup", action = "http://soap.amazon.com")
    public Response<TransactionLookupResponse> transactionLookupAsync(
        @WebParam(name = "TransactionLookup", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
        TransactionLookup body);

    /**
     * 
     * @param body
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "TransactionLookup", action = "http://soap.amazon.com")
    public Future<?> transactionLookupAsync(
        @WebParam(name = "TransactionLookup", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
        TransactionLookup body,
        @WebParam(name = "TransactionLookupResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<TransactionLookupResponse> asyncHandler);

    /**
     * 
     * @param body
     * @return
     *     returns awsClient3.TransactionLookupResponse
     */
    @WebMethod(operationName = "TransactionLookup", action = "http://soap.amazon.com")
    @WebResult(name = "TransactionLookupResponse", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
    public TransactionLookupResponse transactionLookup(
        @WebParam(name = "TransactionLookup", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
        TransactionLookup body);

    /**
     * 
     * @param body
     * @return
     *     returns javax.xml.ws.Response<awsClient3.SellerListingSearchResponse>
     */
    @WebMethod(operationName = "SellerListingSearch", action = "http://soap.amazon.com")
    public Response<SellerListingSearchResponse> sellerListingSearchAsync(
        @WebParam(name = "SellerListingSearch", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
        SellerListingSearch body);

    /**
     * 
     * @param body
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "SellerListingSearch", action = "http://soap.amazon.com")
    public Future<?> sellerListingSearchAsync(
        @WebParam(name = "SellerListingSearch", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
        SellerListingSearch body,
        @WebParam(name = "SellerListingSearchResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<SellerListingSearchResponse> asyncHandler);

    /**
     * 
     * @param body
     * @return
     *     returns awsClient3.SellerListingSearchResponse
     */
    @WebMethod(operationName = "SellerListingSearch", action = "http://soap.amazon.com")
    @WebResult(name = "SellerListingSearchResponse", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
    public SellerListingSearchResponse sellerListingSearch(
        @WebParam(name = "SellerListingSearch", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
        SellerListingSearch body);

    /**
     * 
     * @param body
     * @return
     *     returns javax.xml.ws.Response<awsClient3.SellerListingLookupResponse>
     */
    @WebMethod(operationName = "SellerListingLookup", action = "http://soap.amazon.com")
    public Response<SellerListingLookupResponse> sellerListingLookupAsync(
        @WebParam(name = "SellerListingLookup", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
        SellerListingLookup body);

    /**
     * 
     * @param body
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "SellerListingLookup", action = "http://soap.amazon.com")
    public Future<?> sellerListingLookupAsync(
        @WebParam(name = "SellerListingLookup", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
        SellerListingLookup body,
        @WebParam(name = "SellerListingLookupResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<SellerListingLookupResponse> asyncHandler);

    /**
     * 
     * @param body
     * @return
     *     returns awsClient3.SellerListingLookupResponse
     */
    @WebMethod(operationName = "SellerListingLookup", action = "http://soap.amazon.com")
    @WebResult(name = "SellerListingLookupResponse", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
    public SellerListingLookupResponse sellerListingLookup(
        @WebParam(name = "SellerListingLookup", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
        SellerListingLookup body);

    /**
     * 
     * @param body
     * @return
     *     returns javax.xml.ws.Response<awsClient3.TagLookupResponse>
     */
    @WebMethod(operationName = "TagLookup", action = "http://soap.amazon.com")
    public Response<TagLookupResponse> tagLookupAsync(
        @WebParam(name = "TagLookup", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
        TagLookup body);

    /**
     * 
     * @param body
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "TagLookup", action = "http://soap.amazon.com")
    public Future<?> tagLookupAsync(
        @WebParam(name = "TagLookup", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
        TagLookup body,
        @WebParam(name = "TagLookupResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<TagLookupResponse> asyncHandler);

    /**
     * 
     * @param body
     * @return
     *     returns awsClient3.TagLookupResponse
     */
    @WebMethod(operationName = "TagLookup", action = "http://soap.amazon.com")
    @WebResult(name = "TagLookupResponse", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
    public TagLookupResponse tagLookup(
        @WebParam(name = "TagLookup", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
        TagLookup body);

    /**
     * 
     * @param body
     * @return
     *     returns javax.xml.ws.Response<awsClient3.VehicleSearchResponse>
     */
    @WebMethod(operationName = "VehicleSearch", action = "http://soap.amazon.com")
    public Response<VehicleSearchResponse> vehicleSearchAsync(
        @WebParam(name = "VehicleSearch", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
        VehicleSearch body);

    /**
     * 
     * @param body
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "VehicleSearch", action = "http://soap.amazon.com")
    public Future<?> vehicleSearchAsync(
        @WebParam(name = "VehicleSearch", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
        VehicleSearch body,
        @WebParam(name = "VehicleSearchResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<VehicleSearchResponse> asyncHandler);

    /**
     * 
     * @param body
     * @return
     *     returns awsClient3.VehicleSearchResponse
     */
    @WebMethod(operationName = "VehicleSearch", action = "http://soap.amazon.com")
    @WebResult(name = "VehicleSearchResponse", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
    public VehicleSearchResponse vehicleSearch(
        @WebParam(name = "VehicleSearch", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
        VehicleSearch body);

    /**
     * 
     * @param body
     * @return
     *     returns javax.xml.ws.Response<awsClient3.VehiclePartSearchResponse>
     */
    @WebMethod(operationName = "VehiclePartSearch", action = "http://soap.amazon.com")
    public Response<VehiclePartSearchResponse> vehiclePartSearchAsync(
        @WebParam(name = "VehiclePartSearch", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
        VehiclePartSearch body);

    /**
     * 
     * @param body
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "VehiclePartSearch", action = "http://soap.amazon.com")
    public Future<?> vehiclePartSearchAsync(
        @WebParam(name = "VehiclePartSearch", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
        VehiclePartSearch body,
        @WebParam(name = "VehiclePartSearchResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<VehiclePartSearchResponse> asyncHandler);

    /**
     * 
     * @param body
     * @return
     *     returns awsClient3.VehiclePartSearchResponse
     */
    @WebMethod(operationName = "VehiclePartSearch", action = "http://soap.amazon.com")
    @WebResult(name = "VehiclePartSearchResponse", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
    public VehiclePartSearchResponse vehiclePartSearch(
        @WebParam(name = "VehiclePartSearch", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
        VehiclePartSearch body);

    /**
     * 
     * @param body
     * @return
     *     returns javax.xml.ws.Response<awsClient3.VehiclePartLookupResponse>
     */
    @WebMethod(operationName = "VehiclePartLookup", action = "http://soap.amazon.com")
    public Response<VehiclePartLookupResponse> vehiclePartLookupAsync(
        @WebParam(name = "VehiclePartLookup", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
        VehiclePartLookup body);

    /**
     * 
     * @param body
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "VehiclePartLookup", action = "http://soap.amazon.com")
    public Future<?> vehiclePartLookupAsync(
        @WebParam(name = "VehiclePartLookup", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
        VehiclePartLookup body,
        @WebParam(name = "VehiclePartLookupResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<VehiclePartLookupResponse> asyncHandler);

    /**
     * 
     * @param body
     * @return
     *     returns awsClient3.VehiclePartLookupResponse
     */
    @WebMethod(operationName = "VehiclePartLookup", action = "http://soap.amazon.com")
    @WebResult(name = "VehiclePartLookupResponse", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
    public VehiclePartLookupResponse vehiclePartLookup(
        @WebParam(name = "VehiclePartLookup", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
        VehiclePartLookup body);

    /**
     * 
     * @param body
     * @return
     *     returns javax.xml.ws.Response<awsClient3.MultiOperationResponse>
     */
    @WebMethod(operationName = "MultiOperation", action = "http://soap.amazon.com")
    public Response<MultiOperationResponse> multiOperationAsync(
        @WebParam(name = "MultiOperation", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
        MultiOperation body);

    /**
     * 
     * @param body
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "MultiOperation", action = "http://soap.amazon.com")
    public Future<?> multiOperationAsync(
        @WebParam(name = "MultiOperation", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
        MultiOperation body,
        @WebParam(name = "MultiOperationResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<MultiOperationResponse> asyncHandler);

    /**
     * 
     * @param body
     * @return
     *     returns awsClient3.MultiOperationResponse
     */
    @WebMethod(operationName = "MultiOperation", action = "http://soap.amazon.com")
    @WebResult(name = "MultiOperationResponse", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
    public MultiOperationResponse multiOperation(
        @WebParam(name = "MultiOperation", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2008-10-06", partName = "body")
        MultiOperation body);

}
