#spring.h2.console.enabled=true
# default path: h2-console
#spring.h2.console.path=/h2-ui

## H2
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
#spring.datasource.url=jdbc:h2:file:./testdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=

## logging
logging.level.org.springframework.web=WARN
logging.level.org.hibernate=WARN
logging.level.com.bezkoder.spring=DEBUG
logging.file.name=log/spring-boot-jpa.log
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

## OAuth 2.0
spring.security.oauth2.client.registration.google.client-id=nrkidder
spring.security.oauth2.client.registration.google.client-secret=YOUR_GOOGLE_CLIENT_SECRET
spring.security.oauth2.client.registration.google.scope=openid, profile, email
spring.security.oauth2.client.registration.google.redirect-uri="{baseUrl}/login/oauth2/code/{registrationId}"
provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
provider.google.token-uri=https://oauth2.googleapis.com/token
provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo
provider.google.jwk-set-uri=https://www.googleapis.com/oauth2/v3/certs

## Postgresql
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQL94Dialect
#spring.jpa.database.platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.database=products
spring.datasource.url=jdbc:postgresql://localhost:5432/products
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=products_owner
spring.datasource.password=nju

spring.jpa.show-sql=true
# options are create, create-drop and update (update once the DDL is stable)  BACKUP ALL VIEWS FIRST if doing create or create-drop.  It transforms them into tables.
spring.jpa.hibernate.ddl-auto=update
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Spring Batch
spring.batch.job.names=mediumDocJob,distinctFruitDocJob
spring.batch.jdbc.initialize-schema=always
spring.batch.job.enabled=false
spring.batch.medium.writer.destfile=c:/Users/Computer/training/view_layer/product-list-app/src/assets/mediums.json
spring.batch.distinctfruit.writer.destfile=c:/Users/Computer/training/view_layer/product-list-app/src/assets/distinctFruits.json

# Spring Boot
spring.devtools.restart.enabled=false
server.port=8081
spring.threads.virtual.enabled=true