mv 'Copy of 269.pl'    Copy_of_269.pl    
mv 'Copy of CopyToPageFiles.pl'    Copy_of_CopyToPageFiles.pl    
mv 'Copy of EscSeq.pl'    Copy_of_EscSeq.pl    
mv 'Copy of ExprModifiers.pl'    Copy_of_ExprModifiers.pl    
mv 'Copy of ExprModifiers2.pl'    Copy_of_ExprModifiers2.pl    
mv 'Copy of GoodOpen.pl'    Copy_of_GoodOpen.pl    
mv 'Copy of HighPage.pl'    Copy_of_HighPage.pl    
mv 'Copy of aSlice.pl'    Copy_of_aSlice.pl    
mv 'Copy of accessor1.pl'    Copy_of_accessor1.pl    
mv 'Copy of addElem.pl'    Copy_of_addElem.pl    
mv 'Copy of addressBook.pl'    Copy_of_addressBook.pl    
mv 'Copy of addsizes.pl'    Copy_of_addsizes.pl    
mv 'Copy of argv1.pl'    Copy_of_argv1.pl    
mv 'Copy of argv2.pl'    Copy_of_argv2.pl    
mv 'Copy of argv3.pl'    Copy_of_argv3.pl    
mv 'Copy of arithop1.pl'    Copy_of_arithop1.pl    
mv 'Copy of arithop2.pl'    Copy_of_arithop2.pl    
mv 'Copy of arithop3.pl'    Copy_of_arithop3.pl    
mv 'Copy of arithop4.pl'    Copy_of_arithop4.pl    
mv 'Copy of arithop5.pl'    Copy_of_arithop5.pl    
mv 'Copy of arithop6.pl'    Copy_of_arithop6.pl    
mv 'Copy of arithop7.pl'    Copy_of_arithop7.pl    
mv 'Copy of arithop8.pl'    Copy_of_arithop8.pl    
mv 'Copy of arrayLen.pl'    Copy_of_arrayLen.pl    
mv 'Copy of ascii.pl'    Copy_of_ascii.pl    
mv 'Copy of aside1.pl'    Copy_of_aside1.pl    
mv 'Copy of assignList.pl'    Copy_of_assignList.pl    
mv 'Copy of auto1.pl'    Copy_of_auto1.pl    
mv 'Copy of auto2.pl'    Copy_of_auto2.pl    
mv 'Copy of autoconvert.pl'    Copy_of_autoconvert.pl    
mv 'Copy of backwards.pl'    Copy_of_backwards.pl    
mv 'Copy of badDayArray.pl'    Copy_of_badDayArray.pl    
mv 'Copy of badDayArray2.pl'    Copy_of_badDayArray2.pl    
mv 'Copy of badPrefix.pl'    Copy_of_badPrefix.pl    
mv 'Copy of badhash.pl'    Copy_of_badhash.pl    
mv 'Copy of badnums.pl'    Copy_of_badnums.pl    
mv 'Copy of badopen.pl'    Copy_of_badopen.pl    
mv 'Copy of benchtest1.pl'    Copy_of_benchtest1.pl    
mv 'Copy of benchtest2.pl'    Copy_of_benchtest2.pl    
mv 'Copy of bitop1.pl'    Copy_of_bitop1.pl    
mv 'Copy of bitop2.pl'    Copy_of_bitop2.pl    
mv 'Copy of bless1.pl'    Copy_of_bless1.pl    
mv 'Copy of bless2.pl'    Copy_of_bless2.pl    
mv 'Copy of bool1.pl'    Copy_of_bool1.pl    
mv 'Copy of bool2.pl'    Copy_of_bool2.pl    
mv 'Copy of bool3.pl'    Copy_of_bool3.pl    
mv 'Copy of bool4.pl'    Copy_of_bool4.pl    
mv 'Copy of bool5.pl'    Copy_of_bool5.pl    
mv 'Copy of bool6.pl'    Copy_of_bool6.pl    
mv 'Copy of byref1.pl'    Copy_of_byref1.pl    
mv 'Copy of canLoad1.pl'    Copy_of_canLoad1.pl    
mv 'Copy of canLoad2.pl'    Copy_of_canLoad2.pl    
mv 'Copy of cantLoad.pl'    Copy_of_cantLoad.pl    
mv 'Copy of chess.pl'    Copy_of_chess.pl    
mv 'Copy of classAtr1.pl'    Copy_of_classAtr1.pl    
mv 'Copy of classAtr2.pl'    Copy_of_classAtr2.pl    
mv 'Copy of classAtr3.pl'    Copy_of_classAtr3.pl    
mv 'Copy of colors.pl'    Copy_of_colors.pl    
mv 'Copy of concatFiles.pl'    Copy_of_concatFiles.pl    
mv 'Copy of copy.pl'    Copy_of_copy.pl    
mv 'Copy of count.pl'    Copy_of_count.pl    
mv 'Copy of countdown.pl'    Copy_of_countdown.pl    
mv 'Copy of currency1.pl'    Copy_of_currency1.pl    
mv 'Copy of currency2.pl'    Copy_of_currency2.pl    
mv 'Copy of data1.pl'    Copy_of_data1.pl    
mv 'Copy of data2.pl'    Copy_of_data2.pl    
mv 'Copy of dayarray.pl'    Copy_of_dayarray.pl    
mv 'Copy of defined.pl'    Copy_of_defined.pl    
mv 'Copy of deref1.pl'    Copy_of_deref1.pl    
mv 'Copy of deref2.pl'    Copy_of_deref2.pl    
mv 'Copy of diamond1.pl'    Copy_of_diamond1.pl    
mv 'Copy of die.pl'    Copy_of_die.pl    
mv 'Copy of directory-dir-nocode.pl'    Copy_of_directory-dir-nocode.pl    
mv 'Copy of directory-dir.pl'    Copy_of_directory-dir.pl    
mv 'Copy of directory-glob.pl'    Copy_of_directory-glob.pl    
mv 'Copy of doThis.pl'    Copy_of_doThis.pl    
mv 'Copy of each.pl'    Copy_of_each.pl    
mv 'Copy of elems.pl'    Copy_of_elems.pl    
mv 'Copy of exists.pl'    Copy_of_exists.pl    
mv 'Copy of exit.pl'    Copy_of_exit.pl    
mv 'Copy of explorer.pl'    Copy_of_explorer.pl    
mv 'Copy of fileTest.pl'    Copy_of_fileTest.pl    
mv 'Copy of foreach.pl'    Copy_of_foreach.pl    
mv 'Copy of foreach1.pl'    Copy_of_foreach1.pl    
mv 'Copy of foreach2.pl'    Copy_of_foreach2.pl    
mv 'Copy of foreach3.pl'    Copy_of_foreach3.pl    
mv 'Copy of foreach4.pl'    Copy_of_foreach4.pl    
mv 'Copy of foreach5.pl'    Copy_of_foreach5.pl    
mv 'Copy of foreach6.pl'    Copy_of_foreach6.pl    
mv 'Copy of forloop.pl'    Copy_of_forloop.pl    
mv 'Copy of ftp.pl'    Copy_of_ftp.pl    
mv 'Copy of global1.pl'    Copy_of_global1.pl    
mv 'Copy of global2.pl'    Copy_of_global2.pl    
mv 'Copy of globals1.pl'    Copy_of_globals1.pl    
mv 'Copy of golf.pl'    Copy_of_golf.pl    
mv 'Copy of goodnums.pl'    Copy_of_goodnums.pl    
mv 'Copy of goto.pl'    Copy_of_goto.pl    
mv 'Copy of guessnum1.pl'    Copy_of_guessnum1.pl    
mv 'Copy of guessnum2.pl'    Copy_of_guessnum2.pl    
mv 'Copy of hash.pl'    Copy_of_hash.pl    
mv 'Copy of hashref.pl'    Copy_of_hashref.pl    
mv 'Copy of hello2.pl'    Copy_of_hello2.pl    
mv 'Copy of hello3.pl'    Copy_of_hello3.pl    
mv 'Copy of hellolong.pl'    Copy_of_hellolong.pl    
mv 'Copy of heredoc.pl'    Copy_of_heredoc.pl    
mv 'Copy of hoover.pl'    Copy_of_hoover.pl    
mv 'Copy of ic.pl'    Copy_of_ic.pl    
mv 'Copy of if.pl'    Copy_of_if.pl    
mv 'Copy of index.pl'    Copy_of_index.pl    
mv 'Copy of intoClipboard.pl'    Copy_of_intoClipboard.pl    
mv 'Copy of inventory.pl'    Copy_of_inventory.pl    
mv 'Copy of join.pl'    Copy_of_join.pl    
mv 'Copy of joke1.pl'    Copy_of_joke1.pl    
