
package tcauthClient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "TempConvertAuthImplService", targetNamespace = "http://tcauth.ch05/", wsdlLocation = "file:/home/kalin/jwsur_code/chapter5/tcauth.wsdl")
public class TempConvertAuthImplService
    extends Service
{

    private final static URL TEMPCONVERTAUTHIMPLSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("file:/home/kalin/jwsur_code/chapter5/tcauth.wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        TEMPCONVERTAUTHIMPLSERVICE_WSDL_LOCATION = url;
    }

    public TempConvertAuthImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TempConvertAuthImplService() {
        super(TEMPCONVERTAUTHIMPLSERVICE_WSDL_LOCATION, new QName("http://tcauth.ch05/", "TempConvertAuthImplService"));
    }

    /**
     * 
     * @return
     *     returns TempConvertAuth
     */
    @WebEndpoint(name = "TempConvertAuthImplPort")
    public TempConvertAuth getTempConvertAuthImplPort() {
        return (TempConvertAuth)super.getPort(new QName("http://tcauth.ch05/", "TempConvertAuthImplPort"), TempConvertAuth.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TempConvertAuth
     */
    @WebEndpoint(name = "TempConvertAuthImplPort")
    public TempConvertAuth getTempConvertAuthImplPort(WebServiceFeature... features) {
        return (TempConvertAuth)super.getPort(new QName("http://tcauth.ch05/", "TempConvertAuthImplPort"), TempConvertAuth.class, features);
    }

}
