
package clientTC;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

import clientTC.TempConvert;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "TempConvertService", targetNamespace = "http://tempConvertURI.org/", wsdlLocation = "http://localhost:5599/tc?wsdl")
public class TempConvertService
    extends Service
{

    private final static URL TEMPCONVERTSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://localhost:5599/tc?wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        TEMPCONVERTSERVICE_WSDL_LOCATION = url;
    }

    public TempConvertService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TempConvertService() {
        super(TEMPCONVERTSERVICE_WSDL_LOCATION, new QName("http://tempConvertURI.org/", "TempConvertService"));
    }

    /**
     * 
     * @return
     *     returns TempConvert
     */
    @WebEndpoint(name = "TempConvertPort")
    public TempConvert getTempConvertPort() {
        return (TempConvert)super.getPort(new QName("http://tempConvertURI.org/", "TempConvertPort"), TempConvert.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TempConvert
     */
    @WebEndpoint(name = "TempConvertPort")
    public TempConvert getTempConvertPort(WebServiceFeature... features) {
        return (TempConvert)super.getPort(new QName("http://tempConvertURI.org/", "TempConvertPort"), TempConvert.class, features);
    }

}
