
package clientEJB;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "FibEJBService", targetNamespace = "http://ejb.ch06/", wsdlLocation = "http://localhost:8081/FibEJBService/FibEJB?wsdl")
public class FibEJBService
    extends Service
{

    private final static URL FIBEJBSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8081/FibEJBService/FibEJB?wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        FIBEJBSERVICE_WSDL_LOCATION = url;
    }

    public FibEJBService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FibEJBService() {
        super(FIBEJBSERVICE_WSDL_LOCATION, new QName("http://ejb.ch06/", "FibEJBService"));
    }

    /**
     * 
     * @return
     *     returns Fib
     */
    @WebEndpoint(name = "FibEJBPort")
    public Fib getFibEJBPort() {
        return (Fib)super.getPort(new QName("http://ejb.ch06/", "FibEJBPort"), Fib.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Fib
     */
    @WebEndpoint(name = "FibEJBPort")
    public Fib getFibEJBPort(WebServiceFeature... features) {
        return (Fib)super.getPort(new QName("http://ejb.ch06/", "FibEJBPort"), Fib.class, features);
    }

}
