
package client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "TimeServerService", targetNamespace = "http://tsd.ch02/", wsdlLocation = "http://localhost:7777/tsd?wsdl")
public class TimeServerService
    extends Service
{

    private final static URL TIMESERVERSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://localhost:7777/tsd?wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        TIMESERVERSERVICE_WSDL_LOCATION = url;
    }

    public TimeServerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TimeServerService() {
        super(TIMESERVERSERVICE_WSDL_LOCATION, new QName("http://tsd.ch02/", "TimeServerService"));
    }

    /**
     * 
     * @return
     *     returns TimeServer
     */
    @WebEndpoint(name = "TimeServerPort")
    public TimeServer getTimeServerPort() {
        return (TimeServer)super.getPort(new QName("http://tsd.ch02/", "TimeServerPort"), TimeServer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TimeServer
     */
    @WebEndpoint(name = "TimeServerPort")
    public TimeServer getTimeServerPort(WebServiceFeature... features) {
        return (TimeServer)super.getPort(new QName("http://tsd.ch02/", "TimeServerPort"), TimeServer.class, features);
    }

}
