export const STATES: string[] = ['', 'AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DE', 'FL', 'GA', 'HI', 'IA', 'ID', 'IL', 'IN', 'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH', 'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA', 'VT', 'WA', 'WI', 'WV', 'WY'];
export const LOT_CNTS: number[] = [0, 4, 6, 12, 24, 36, 48, 60, 72, 96, 120, 144, 192];
export const ORDER_STATUSES = ["New", "In Process", "Cancelled", "Completed"] as const;
export const STATE_TAX_RATES = [
    { state: "AK", rate: 0 },
    { state: "AL", rate: 0.04 },
    { state: "AR", rate: 0.065 },
    { state: "AZ", rate: 0.056 },
    { state: "CA", rate: 0.0725 },
    { state: "CO", rate: 0.029 },
    { state: "CT", rate: 0.0635 },
    { state: "DE", rate: 0 },
    { state: "FL", rate: 0.06 },
    { state: "GA", rate: 0.04 },
    { state: "HI", rate: 0.04 },
    { state: "IA", rate: 0.06 },
    { state: "ID", rate: 0.06 },
    { state: "IL", rate: 0.0625 },
    { state: "IN", rate: 0.07 },
    { state: "KS", rate: 0.065 },
    { state: "KY", rate: 0.06 },
    { state: "LA", rate: 0.05 },
    { state: "MA", rate: 0.0625 },
    { state: "MD", rate: 0.06 },
    { state: "ME", rate: 0.055 },
    { state: "MI", rate: 0.06 },
    { state: "MN", rate: 0.0688 },
    { state: "MO", rate: 0.0423 },
    { state: "MS", rate: 0.07 },
    { state: "MT", rate: 0 },
    { state: "NC", rate: 0.0475 },
    { state: "ND", rate: 0.05 },
    { state: "NE", rate: 0.055 },
    { state: "NH", rate: 0 },
    { state: "NJ", rate: 0.0663 },
    { state: "NM", rate: 0.0513 },
    { state: "NV", rate: 0.046 },
    { state: "NY", rate: 0.04 },
    { state: "OH", rate: 0.0575 },
    { state: "OK", rate: 0.045 },
    { state: "OR", rate: 0 },
    { state: "PA", rate: 0.06 },
    { state: "RI", rate: 0.07 },
    { state: "SC", rate: 0.06 },
    { state: "SD", rate: 0.045 },
    { state: "TN", rate: 0.07 },
    { state: "TX", rate: 0.0625 },
    { state: "UT", rate: 0.047 },
    { state: "VA", rate: 0.043 },
    { state: "VT", rate: 0.06 },
    { state: "WA", rate: 0.065 },
    { state: "WI", rate: 0.05 },
    { state: "WV", rate: 0.06 },
    { state: "WY", rate: 0.04 }
] as const;